nuclia/frontend

apps/app/src/environments/environment.prod.ts, apps/app/src/environments/environment.ts, libs/core/src/lib/analytics/index.ts, libs/core/src/lib/analytics/post-hog.service.spec.ts, libs/core/src/lib/analytics/post-hog.service.ts, libs/core/src/lib/analytics/tracking.service.ts, libs/core/src/lib/api/sdk.service.ts, libs/core/src/lib/config/app.init.service.ts
- Create PostHog service and use it in tracking service
- Get post hog feature-flag for demo kb id
- Remove demo kb id from environments
Feature flag for stashify: https://track.stashify.cloud/feature_flags/18
Feature flags for production: https://track.nuclia.cloud/feature_flags/15
=> Manage demo kb id in posthog

apps/dashboard/src/app/knowledge-box/knowledge-box-process/knowledge-box-processes.component.html, apps/dashboard/src/app/knowledge-box/knowledge-box-process/knowledge-box-processes.component.spec.ts, apps/dashboard/src/app/knowledge-box/knowledge-box-process/knowledge-box-processes.component.ts, apps/dashboard/src/app/knowledge-box/knowledge-box.module.ts, package.json, yarn.lock
- Hide payment related messages in training control panel when feature flag is disabled
- Add ng-mocks dep to fix missing element errors in KnowledgeBoxProcessComponent tests
- Use Pastanaga buttons and checkboxes instead of STF ones in KnowledgeBoxProcessComponent
=> [sc-2024]: Hide payment related messages in training control panel

apps/dashboard/src/app/widgets/edit/edit-widget.component.html, apps/dashboard/src/app/widgets/edit/edit-widget.component.scss, apps/dashboard/src/app/widgets/edit/edit-widget.component.ts, apps/dashboard/src/app/widgets/widgets.module.ts
Renaming a widget is not allowed byt the backend, so we have to delete and re-create it with the new id.
=> Fix [sc-1842]: rename widget

libs/search-widget/src/viewer/Metadata.svelte
- Fix [sc-1954]: Don't display empty entities in widget preview
- Cleanup summaries initialization to prevent eslint error
=> Fix [sc-1954]: Don't display empty entities in widget preview

apps/dashboard/src/app/knowledge-box/knowledge-box/knowledge-box.component.ts
Not sure those changes will fix the issue as I wasn't able to reproduce it, but seeing the takeUntil misplaced made me think that could have been related.
=> [sc-2090]: prevent empty kb dialog to popup when kb not empty

apps/dashboard/src/app/account/account-kbs/account-kbs.component.html, apps/dashboard/src/app/account/account-users/account-users.component.html, apps/dashboard/src/app/components/stash-navbar/stash-navbar.component.html, apps/dashboard/src/app/components/stash-navbar/stash-navbar.component.scss, apps/dashboard/src/app/knowledge-box/knowledge-box-users/users-manage/users-manage.component.html, apps/dashboard/src/app/knowledge-box/knowledge-box-users/users-manage/users-manage.component.ts, libs/common/src/assets/i18n/en.json, libs/core/src/lib/models/users.model.ts
Disable delete button on:
- the only user left for this kb
- the only owner of the KB (we can delete an owner of a KB only if there is another owner on the kb)
Disable select role of a user when:
- the user is not an account manager
- the user is an account manager but the user is the only owner of the kb
Fix disabled style in the navbar
=> [sc-2107] prevent removing the last user of a kb

apps/dashboard/src/app/account/account.module.ts, apps/dashboard/src/app/widgets/widgets.module.ts, apps/desktop/src/app/connectors/connectors.module.ts, mrs.developer.json
With Pastanaga 2.55.1 PaTextFieldModule is enough for using <pa-option> with <pa-select>
=> Fix [sc-1999]: don't import PaDropdownModule for pa-select

libs/sdk-core/src/lib/db/resource.ts, libs/search-widget/src/viewer/Viewer.svelte, libs/search-widget/src/viewer/store.ts
In the resource viewer of the widget, if a search request fails:
- An error message is displayed
- The user can try another query
=> [sc-1952] Show error message when searching on a resource fails

libs/search-widget/src/widgets/row/Row.svelte
- Display the thumbnails without modifying its aspect ratio or cropping the image.
- Add a background color to the thumbnails container, so that all thumbnails look uniform.
=> [sc-2111] Modify thumbnail dimensions in search results

libs/search-widget/src/_video-widget/ParagraphPlayer.svelte, libs/search-widget/src/_video-widget/TimePlayer.svelte, libs/search-widget/src/_video-widget/VideoTile.svelte, libs/search-widget/src/core/utils.ts
- revert [sc-2260]: keep the time visible on desktop
- Make full paragraph line clickable 
- Display timestamp on 4 digits minimum
=> [sc-2260] video tile improvements timing on hover

libs/search-widget/src/_video-widget/ThumbnailPlayer.svelte, libs/search-widget/src/_video-widget/VideoTile.scss, libs/search-widget/src/_video-widget/VideoTile.svelte
Svelte transitions are working only within an if block
=> Fix [sc-2338]: prevent HTML remainder from bad transition

libs/search-widget/src/_video-widget/ParagraphPlayer.scss, libs/search-widget/src/_video-widget/SearchResults.scss, libs/search-widget/src/_video-widget/SearchResults.svelte, libs/search-widget/src/_video-widget/ThumbnailPlayer.svelte, libs/search-widget/src/_video-widget/TimePlayer.scss, libs/search-widget/src/_video-widget/VideoTile.scss, libs/search-widget/src/_video-widget/VideoTile.svelte, libs/search-widget/src/_video-widget/transition.utils.ts, libs/search-widget/src/common-style.scss, libs/search-widget/src/components/button/Button.scss, libs/search-widget/src/components/toggle/toggle.scss, libs/search-widget/src/viewer/ActionMenu.scss, libs/search-widget/src/viewer/Header.scss, libs/search-widget/src/viewer/InputViewer.scss, libs/search-widget/src/viewer/LabelMenu.scss, libs/search-widget/src/widgets/results/Results.scss, libs/search-widget/src/widgets/row/Thumbnail.scss, libs/search-widget/src/widgets/row/Thumbnail.svelte, libs/search-widget/src/widgets/search-input/SearchInput.scss, libs/search-widget/src/widgets/suggestions/Suggestions.scss
* Search results improvements
- align all content to the top of the video
- keep the same font size for titles on desktop and on mobile (font-size: 18px, line-height: 26px)
* Fix scrolling behavior on fullscreen preview
* Scrollable area doesn't include find bar and collapsed search results
* Search results: display video and texts at the same time
* Fix thumbnail loading transition and height
* Fix selected paragraph
* Hovering paragraph improvements
- Search results: round corners on both sides
- Video tile: full width paragraph in transcripts
- Background transition on TimePlayer and ParagraphPlayer 
* Fix show-all-results transition
* Search results – let a bit less space between videos
- There is some white space above and below the video thumbnail because the thumbnail height is …
=> [sc-2342] video tile improvements

libs/search-widget/src/core/api.ts, libs/search-widget/src/core/models.ts, libs/search-widget/src/core/old-stores/main.store.ts, libs/search-widget/src/core/search-bar.ts, libs/search-widget/src/core/stores/suggestions.store.ts, libs/search-widget/src/core/stores/widget.store.ts, libs/search-widget/src/old-components/embedded-search/EmbeddedSearch.scss, libs/search-widget/src/old-components/embedded-search/EmbeddedSearch.spec.ts, libs/search-widget/src/old-components/embedded-search/EmbeddedSearch.svelte, libs/search-widget/src/old-components/popup-search/PopupSearch.scss, libs/search-widget/src/old-components/popup-search/PopupSearch.spec.ts, libs/search-widget/src/old-components/popup-search/PopupSearch.svelte, libs/search-widget/src/old-components/search-input/SearchInput.scss, libs/search-widget/src/old-components/search-input/SearchInput.spec.ts, libs/search-widget/src/old-components/search-input/SearchInput.svelte, libs/search-widget/src/old-components/suggestions/Suggestions.svelte, libs/search-widget/src/old-components/viewer/Header.svelte, libs/search-widget/src/old-components/viewer/menus/ActionMenu.svelte, libs/search-widget/src/old-components/viewer/paragraphs/ParagraphWithMenu.svelte, libs/search-widget/src/widgets/search-widget/Widget.svelte
- Move widget data in their own store
- Manage suggestions dropdown directly from search-input
- The same code was duplicated on EmbeddedSearch and PopupSearch, while suggestion is a feature belonging to the SearchInput
- New store for suggestions
=> [sc 2522] widget and suggestion stores

libs/search-widget/src/common/modal/ConfirmDialog.svelte, libs/search-widget/src/common/modal/Modal.svelte, libs/search-widget/src/common/modal/modal.utils.ts, libs/search-widget/src/tiles/_tile.scss, libs/search-widget/src/tiles/pdf-tile/PdfTile.svelte, libs/search-widget/src/tiles/video-tile/VideoTile.svelte, libs/search-widget/src/widgets/search-video-widget/SearchResults.svelte
- Use `position: fixed` on expanded tiles
- Create common `freezeBackground` and `unblockBackground` functions used by all our modals (based on https://css-tricks.com/prevent-page-scrolling-when-a-modal-is-open/)
- Freeze the background when tile is expanded
- Unblock the background when expanded tile is closed
=> Fix [sc-2936]: display expanded tiles properly

apps/search-widget-demo/src/App.svelte, libs/sdk-core/CHANGELOG.md, libs/sdk-core/src/lib/db/search/filter.ts, libs/sdk-core/src/lib/db/search/index.ts, libs/search-widget/src/common/label/label.utils.ts, libs/search-widget/src/core/models.ts, libs/search-widget/src/core/old-stores/main.store.ts, libs/search-widget/src/core/search-bar.ts, libs/search-widget/src/core/stores/effects.ts, libs/search-widget/src/core/stores/suggestions.store.ts, libs/search-widget/src/old-components/search-input/SearchInput.scss, libs/search-widget/src/old-components/search-input/SearchInput.svelte, libs/search-widget/src/old-components/suggestions/Suggestions.svelte, libs/search-widget/src/widgets/search-widget/Widget.svelte
- Remove intent layer in suggestions to have labels directly
- Add suggested label to filters on click
- Store the filter string directly instead of an encoded filter query
- Remove the support for encoded filter query from search input
- Remove `activateFilters` effect and trigger search directly from `searchBy(label: Classification)` function
- Display filters on the right of popup search input
=> [sc 3035] add suggested label as filter

apps/dashboard/src/app/ontologies/ontology-list/ontology-list.component.html, apps/dashboard/src/app/ontologies/ontology-list/ontology-list.component.scss
- Display an ellipsis and a tooltip for long labelsets and labels name in classification page
- use rhythm and sistema colors
=> Fix [sc-3173]: ellipsis and tooltip for long label set names

libs/sdk-core/CHANGELOG.md, libs/sdk-core/src/lib/db/upload.ts, libs/sdk-core/src/lib/rest/rest.ts
- Always set content_type in upload metadata
- Don't parse the body of a post request when `specialContentType` is set, even if special `content-type` is set to `application/json`
=> Fix content-type on upload & fix upload of json files

apps/dashboard/src/app/account/account-manage/account-delete/account-delete.component.html, mrs.developer.json
Use the new `noEllipsis` option on the checkbox used for asking account deletion confirmation
=> Fix [sc-3457]: Display account deletion confirmation entirely

libs/search-widget/src/common/icons/Icon.svelte, libs/search-widget/src/widgets/search-video-widget/SearchBar.svelte, libs/search-widget/src/widgets/search-widget/Widget.svelte, libs/search-widget/src/widgets/viewer-widget/ViewerWidget.svelte
- There was a race condition: our svg sprite was loaded in the DOM slightly after the SearchInput, so the icons in SearchInput was not loaded in the DOM.
- cleanup Icon component: During the investigations, we realised we were using deprecated HTML code (`xlink:href`) and useless `xmlns:xlink`
=> Fix [sc-3459]: display icons in Safari

apps/dashboard/src/app/resources/resource-list.component.ts, libs/sdk-core/CHANGELOG.md, libs/sdk-core/package.json, libs/sdk-core/src/lib/db/search/search.models.ts, libs/sdk-core/src/lib/db/search/search.ts
- Sort option on search is now an object.
- Add corresponding `SortOption` interface and `SortOrder` type in our model.
- Improve serialization in search to support options from object (like sort)
=> Fix search query in resource list

apps/search-widget-demo/src/App.svelte, libs/sdk-core/CHANGELOG.md, libs/sdk-core/src/lib/db/search/search.models.ts, libs/search-widget/src/core/stores/search.store.spec.ts, libs/search-widget/src/core/stores/search.store.ts
Add field property to SmartResult, and make sure SmartResult list has one entry by field. This way we can have several tiles for one resource if some results are coming from different fields of the resource.
And fix https://app.shortcut.com/flaps/story/3827/merging-paragraph-and-sentence-search-results-may-have-duplicates
=> [sc-3675] Refactor results by fields

apps/search-widget-demo/src/App.svelte, libs/search-widget/src/common/player/AudioPlayer.svelte, libs/search-widget/src/old-components/viewer/previewers/Player.svelte, libs/search-widget/src/tiles/audio-tile/AudioTile.svelte, libs/search-widget/src/tiles/video-tile/VideoTile.svelte
- fix ThumbnailPlayer event listener so clicking on the thumbnail starts the video/audio
- toggle mediaLoading when audio is ready so audio player is displayed
- fix play from paragraph and from transcript on audio tile
- fix play from 0
- add ability to play/pause audio with space key
=> Fix [sc-3807]: audio tile

app.babel, apps/dashboard/src/app/resources/resource-list.component.html, apps/dashboard/src/app/resources/resource-list.component.ts, libs/common/src/assets/i18n/ca.json, libs/common/src/assets/i18n/en.json, libs/common/src/assets/i18n/es.json
- Display only resources processed at least once on processed page, even if processing failed or if processing is happening again
- On processing and failure views, filter resources by status
- Fix Classification column title
=> Fix error view on resource list

apps/dashboard/src/app/resources/edit/classification/paragraph-classification/paragraph-classification.component.ts, apps/dashboard/src/app/resources/edit/edit-resource.helpers.spec.ts, apps/dashboard/src/app/resources/edit/edit-resource.helpers.ts
- Don't send empty classification array in the payload to prevent 422 error `{"detail":"ensure classifications has at least 1 items"}` from the backend
- Prevent success toast to show up several times when switching field view
=> Fix paragraph classification bugs on save

apps/dashboard/src/app/knowledge-box/knowledge-box-training/knowledge-box-training.component.ts
Last two merged PRs were not deployed because of a problem on jenkins, this useless change is to allow a new build and deploy.
=> Moving line around to trigger build and deploy dashboard

apps/dashboard/src/app/resources/resource-list.component.html, apps/dashboard/src/app/resources/resource-list.component.ts, apps/dashboard/src/app/resources/sample-dataset/dataset-import.component.html
- Use data from `/counter` endpoint to check if the knowledge box is empty (at the moment it's more robust than using`fulltext.facets`)
=> [sc-4030] Dataset import proposed when not empty

apps/dashboard/src/app/upload/create-link/create-link.component.ts, apps/dashboard/src/app/upload/upload.service.ts, libs/sdk-core/CHANGELOG.md, libs/sdk-core/src/lib/db/kb/kb.models.ts, libs/sdk-core/src/lib/db/kb/kb.ts
- Set resource `origin.url` property when creating links from the dashboard
- Don't set `origin.url` when the link is a YouTube video
=> [sc-4106] set resource origin when uploading links

libs/search-widget/src/tiles/base-tile/BaseTile.svelte, libs/search-widget/src/tiles/viewers/PdfViewer.svelte
- Fix expanded tile side panel search
- hide main search result navigator when the side panel is open
- don't reset `viewerSearchQuery` with main search query when clicking on a paragraph
- initialize viewer search query with main query on
- Fix PDF viewer
- don't change current scale when opening the side panel
- use page-fit scale only for mobile (use auto-scale otherwise)
=> [sc-4262] Fix search and pdf viewer in expanded tile 

apps/dashboard/src/app/knowledge-box/knowledge-box-home/knowledge-box-home.component.scss, apps/dashboard/src/app/knowledge-box/knowledge-box-keys/knowledge-box-keys.component.scss, apps/dashboard/src/app/knowledge-box/knowledge-box-profile/knowledge-box-profile.component.scss, apps/dashboard/src/app/knowledge-box/knowledge-box-training/knowledge-box-training.component.scss, apps/dashboard/src/app/knowledge-box/knowledge-box-training/training-history/training-history.component.scss, apps/dashboard/src/app/knowledge-box/knowledge-box-users/users-manage/users-manage.component.scss, apps/dashboard/src/app/knowledge-box/knowledge-box/knowledge-box.component.scss, apps/dashboard/src/app/knowledge-box/service-access/service-access.component.scss, libs/common/src/lib/label/label-sets/label-set-list/label-set-list.component.scss, libs/common/src/lib/label/label-sets/label-set/color-picker/color-picker.component.scss, libs/common/src/lib/label/label-sets/label-set/label-set.component.scss, libs/common/src/lib/label/label-sets/label-set/label/label.component.scss, libs/common/src/lib/pagination/pagination.component.scss, libs/common/src/lib/select-account-kb/select-account/select-account.component.scss, libs/common/src/lib/upload/upload-bar/upload-bar.component.scss, libs/common/src/lib/user/_user-layout.scss, libs/common/src/lib/user/check-mail/check-mail.component.scss, libs/common/src/lib/user/consent/consent.component.scss, libs/common/src/lib/user/login/login.component.scss, libs/common/src/lib/user/onboarding/onboarding.component.scss, libs/common/src/lib/user/profile/profile.component.scss, libs/common/src/lib/user/recover/recover.component.scss, libs/common/src/lib/user/reset/reset.component.scss, libs/common/src/lib/user/signup/signup.component.scss, libs/common/src/lib/user/sso/sso-button.component.scss, libs/common/src/lib/user/user-container/user-container.component.scss
We don't want big relative paths for scss variables import, and we don't want errors in our IDEs which are not finding the global `@import 'variables';` in our libs (because variables is defined in each app).
Knowing our variables are always the same whatever the app, we decided to reference the absolute path of dashboard's variables in common lib.
=> Fix scss variables import in common lib

apps/dashboard/src/app/knowledge-box/service-access/service-access.component.html, libs/common/src/lib/resources/edit/preview/preview.component.ts
1. During contributor app creation, I commented a bunch of code to debug a compilation problem I had and I forgot to uncomment service-access.component.html.
2. Our viewer widget doesn't manage well undefined inputs, so we should not set standalone input at all when creating the viewer snippet in the dashboard.
=> Fix dashboard's preview and uncomment service-access

libs/sistema/src/lib/dropdown-button/dropdown-button.component.ts
Dropdown button was not handling resetting icon to empty string properly
=> Fix kb-switch so the lock icon is not displayed by mistake

apps/search-widget-demo/src/App.svelte, libs/common/src/lib/resources/edit-resource/paragraph.service.ts, libs/common/src/lib/resources/resource-list/error-resources-table/error-resources-table.component.ts, libs/common/src/lib/resources/resource-list/processed-resource-table/processed-resource-table.component.spec.ts, libs/common/src/lib/resources/resource-list/resource-list.component.ts, libs/common/src/lib/resources/sample-dataset/sample-dataset.service.ts, libs/sdk-core/CHANGELOG.md, libs/sdk-core/package.json, libs/sdk-core/src/lib/db/kb/kb.models.ts, libs/sdk-core/src/lib/db/kb/kb.ts, libs/sdk-core/src/lib/db/resource/resource.ts, libs/sdk-core/src/lib/db/search/search.models.ts, libs/sdk-core/src/lib/db/search/search.ts, libs/sdk-core/src/lib/models.ts, libs/search-widget/public/i18n/ca.json, libs/search-widget/public/i18n/en.json, libs/search-widget/public/i18n/es.json, libs/search-widget/public/i18n/fr.json, libs/search-widget/src/components/suggestions/Suggestions.scss, libs/search-widget/src/components/suggestions/Suggestions.svelte, libs/search-widget/src/core/api.ts, libs/search-widget/src/core/models.ts, libs/search-widget/src/core/stores/search.store.ts, libs/search-widget/src/core/stores/suggestions.store.ts, libs/search-widget/src/tiles/base-tile/BaseTile.svelte, libs/search-widget/src/tiles/base-tile/header/TileHeader.svelte, libs/search-widget/src/widgets/search-widget/SearchResults.svelte, libs/search-widget/widget.babel
- Prevent resource title to overlap header actions
- [sc-4882] and [sc-4639]: better error state management
- If http error 402, display proper message on search widget
- Refactor search endpoints (search, find, catalog, suggest) and states to use a common `IErrorResponse` interface and return error status and detail
=> [sc-4882] and [sc-4639] Better error management on search

app.babel, apps/dashboard/src/app/account/account-kbs/account-kbs.component.html, apps/dashboard/src/app/account/account-kbs/account-kbs.component.scss, libs/common/src/assets/i18n/ca.json, libs/common/src/assets/i18n/en.json, libs/common/src/assets/i18n/es.json, libs/common/src/lib/resources/edit-resource/classification/paragraph-classification/paragraph-classification.component.html, libs/common/src/lib/resources/edit-resource/classification/paragraph-classification/paragraph-classification.component.scss
Fix:
- https://app.shortcut.com/flaps/story/3337/description-for-account-s-knowledge-boxes
- https://app.shortcut.com/flaps/story/4918/add-a-small-description-about-how-to-use-paragraph-classification
=> Fix [sc-3337]: add description on account kb list

apps/dashboard/src/app/account/account-nua/client-dialog/client-dialog.component.html, apps/dashboard/src/app/knowledge-box/service-access/service-access.component.html, libs/common/src/lib/hint/hint.component.html, libs/common/src/lib/hint/hint.component.scss, libs/common/src/lib/hint/hint.component.ts, libs/common/src/lib/hint/hint.module.ts, libs/common/src/lib/resources/edit-resource/profile/profile.component.html, libs/common/src/lib/upload/upload-files/upload-files.component.html
Hint component refactoring so:
- it displays a copy button when there is some code (ie `pre>code` elements) present
- it has a new input `learnMore` to show a generic learn more link.
=> [sc-4459] Add an icon to copy the code on hint component

apps/dashboard/src/app/knowledge-box/knowledge-box-users/users-manage/users-manage.component.html, apps/dashboard/src/app/knowledge-box/knowledge-box-users/users-manage/users-manage.component.ts
Prettier was reformatting the `disabled` expression in a way which changed it outcome. Small refactoring preventing this problem
=> Fix [sc-4935]: enable delete user button

apps/manager-v2/src/app/manage-accounts/account-details/account-details.component.html, libs/common/src/lib/search/search.component.ts, libs/search-widget/src/core/stores/effects.ts, libs/search-widget/src/core/utils.ts
- When there is an anchor it includes the query params and `location.search` is empty, so we created `getUrlParams` function which get the params from the hash or the search depending on which one is present. We also updated `updateQueryParams` function to keep the hash part on the URL.
- Small fix on [sc-5464]: Prevent account id to be wrapped on 2 lines
=> [sc 5444] Search widget permalink is erasing url anchor

libs/search-widget/src/widgets/search-widget/SearchResults.svelte
For e2e, we need to be able to discriminate tiles from initial answer from those from the main search. To do so, we need to wrap the main search results in a div containing a selector (the class `.search-results`).
=> Add search results discriminator [sc-5104]

libs/common/src/lib/resources/resource-list/resource-list.component.html, libs/common/src/lib/resources/resource-list/resource-list.component.ts
and don't show "empty kb – import sample dataset" when there is a query
=> Fix [sc-5497]: Escape dot in resource search

libs/common/src/lib/upload/upload-files/upload-files.component.ts, libs/search-widget/src/core/stores/viewer.store.ts, libs/search-widget/src/tiles/VideoTile.svelte
Fixes:
- Properly recognize mkv files on file upload. (e.g. macOS doesn't recognize them)
- Make mkv fields playable in the search widget
=> [sc-5786] mkv are not identified as media files

apps/dashboard/src/app/account/account-home/account-home.component.ts, apps/dashboard/src/app/account/billing/billing.models.ts, apps/dashboard/src/app/account/billing/billing.service.ts, apps/dashboard/src/app/account/billing/checkout/checkout.component.ts, apps/dashboard/src/app/account/billing/subscriptions/subscriptions.component.ts, apps/manager-v2/src/app/manage-accounts/account-details/account-details.component.html, apps/manager-v2/src/app/manage-accounts/account-details/blocked-features/blocked-features.component.html, apps/manager-v2/src/app/manage-accounts/account-details/blocked-features/blocked-features.component.spec.ts, apps/manager-v2/src/app/manage-accounts/account-details/blocked-features/blocked-features.component.ts, apps/manager-v2/src/app/manage-accounts/account-details/blocked-features/feature-name.pipe.ts, apps/manager-v2/src/app/manage-accounts/account-details/configuration/configuration.component.html, apps/manager-v2/src/app/manage-accounts/account-details/configuration/configuration.component.scss, apps/manager-v2/src/app/manage-accounts/account-details/configuration/configuration.component.spec.ts, apps/manager-v2/src/app/manage-accounts/account-details/configuration/configuration.component.ts, apps/manager-v2/src/app/manage-accounts/account-details/limits/limits.component.html, apps/manager-v2/src/app/manage-accounts/account-details/limits/limits.component.scss, apps/manager-v2/src/app/manage-accounts/account-details/limits/limits.component.spec.ts, apps/manager-v2/src/app/manage-accounts/account-details/limits/limits.component.ts, apps/manager-v2/src/app/manage-accounts/account-list/account-list.component.spec.ts, apps/manager-v2/src/app/manage-accounts/account.models.ts, apps/manager-v2/src/app/manage-accounts/account.service.ts, apps/manager-v2/src/app/manage-accounts/manage-accounts.module.ts, apps/manager-v2/src/app/manage-users/user-list/user-list.component.spec.ts, apps/manager-v2/src/styles.scss, libs/core/src/lib/api/account.service.ts, libs/core/src/lib/api/index.ts, libs/core/src/lib/models/account.model.ts, libs/sdk-core/CHANGELOG.md, libs/sdk-core/src/lib/db/db.models.ts, mrs.developer.json
- Field indexer_slow_replicas has been deprecated and should be replaced for the max_dedicated_processors field
- it would be necessary to review that all those fields corresponding to numerical values ​​must be sent as integers instead of being sent as strings
- Limits fields `monthly_limit_chars_processed` and `monthly_limit_non_media_files_processed` are no longer needed, so both could be removed from the limits form
- rethink and implement a different way to set the limits in the limits form (can be `number > 0`,` -1` or `null`)
- provide an option to reset all limits to default values OR unlimited? (this will probably what Eudald uses the most)
- add and manage optional `trial_expiration_date` on account details that can be updated.
- The amount of blocked features has been extended …
=> [sc-5763] adjust manager app to address latest features

apps/manager-v2/src/app/manage-accounts/account-details/configuration/configuration.component.html, apps/manager-v2/src/app/manage-accounts/account-details/configuration/configuration.component.ts
- When modifying an account in the manage, the `trial_expiration_date` param is only included in the payload if the current account is trial.
- `trial_expiration_date` is not included in the payload when downgrading from enterprise to trial account.
=> [sc-5872] patch expiration date only when account is trial

apps/desktop/src/app/account/account.component.ts, apps/desktop/src/app/main-layout/main-layout.component.ts, package.json
In some corner cases happening only for people having several accounts on several environment (ie Stage and Prod), the Desktop ended up in a bad state where no account was selected. This PR is adding more checks and redirections to prevent this from happening.
Steps I followed to reproduce the bug:
1. in the browser, open and log in stage in a tab and nuclia.cloud (prod) in another tab
2. open Desktop app (the one I downloaded from Prod dashboard), log in, choose a prod account and then quit Desktop app
3. build Desktop locally and open it: 
- the app logs in automatically without showing the select an account page
- the current account won't show up on the top bar even if you have several accounts
- if you try to add a connector, on the select destination step there will be no kb …
=> Fix [sc-5861]: Prevent bad account selection

libs/search-widget/src/widgets/search-widget/SearchBar.svelte
- Provide `europe-1` as default `zone`
- Make `knowledgebox` mandatory (will warn on the console if not provided)
- Make `cdn` and `apikey` optional (no warning on the console when not provided)
=> Fix widget inputs to warn only on mandatory ones

libs/sdk-core/CHANGELOG.md, libs/sdk-core/src/lib/db/kb/kb.models.ts, libs/sdk-core/src/lib/db/kb/kb.ts, libs/sdk-core/src/lib/db/search/chat.models.ts, libs/sdk-core/src/lib/db/search/chat.ts, libs/sdk-core/src/lib/models.ts, libs/sdk-core/src/lib/rest/rest.ts, libs/search-widget/public/i18n/ca.json, libs/search-widget/public/i18n/en.json, libs/search-widget/public/i18n/es.json, libs/search-widget/public/i18n/fr.json, libs/search-widget/src/components/answer/InitialAnswer.svelte, libs/search-widget/src/core/api.ts, libs/search-widget/src/core/stores/answers.store.ts, libs/search-widget/src/core/stores/effects.ts, libs/search-widget/src/core/stores/search.store.ts, libs/search-widget/widget.babel
- `chat` method from the sdk returns a `IErrorResponse` like `find` and `search` methods
- Display chat errors on search widget
=> [sc-6029] [sc-6044] manage chat endpoint errors

libs/sdk-core/CHANGELOG.md, libs/sdk-core/src/lib/db/search/search.models.ts, libs/search-widget/src/components/answer/Answer.svelte, libs/search-widget/src/core/api.ts, libs/search-widget/src/core/models.ts, libs/search-widget/src/core/search-bar.ts, libs/search-widget/src/core/stores/search.store.ts, libs/search-widget/src/tiles/AudioTile.svelte, libs/search-widget/src/tiles/ConversationTile.svelte, libs/search-widget/src/tiles/ImageTile.svelte, libs/search-widget/src/tiles/PdfTile.svelte, libs/search-widget/src/tiles/SpreadsheetTile.svelte, libs/search-widget/src/tiles/TextTile.svelte, libs/search-widget/src/tiles/Tile.svelte, libs/search-widget/src/tiles/VideoTile.svelte, libs/search-widget/src/tiles/base-tile/BaseTile.svelte, libs/search-widget/src/tiles/base-tile/DocumentTile.svelte, libs/search-widget/src/tiles/base-tile/MediaTile.svelte, libs/search-widget/src/widgets/search-widget/SearchResults.svelte, libs/search-widget/src/widgets/viewer-widget/ViewerWidget.svelte
- Update `getSortedResults` to return one SmartResult entry by field
- Update the state to store the resources coming from the results as a list in `resourceList` so we can concatenate them when loading more
- Don't show duplicated results
- Store resultList in the state
- Rename search models without `smart` prefix
- Refactor search state to store results as a list of sorted `FieldResults`
- Fix generative answer bug which was writing in the state a lot while the answer was streaming
=> [sc-6139] Search results: display one tile by field

apps/dashboard/src/app/account/billing/calculator/calculator.component.html, apps/dashboard/src/app/account/billing/checkout/checkout.component.ts, apps/dashboard/src/app/account/billing/subscriptions/subscriptions.component.ts
Until cancellation flow is implemented, all cancelation emails should go to "support@nuclia.com" instead of "billing@..."
=> Billing email address change to support for now

apps/manager-v2/src/app/manage-accounts/account-details/configuration/configuration.component.ts
When the user set 0 `max_dedicated_processors` for an account that has dedicated processors ENABLED, the rule to take in consideration is that an account with enabled dedicated processors must have at least 1 max dedicated processor. On the server side this value is automatically coerced to 1 to comply with the rule.
=> [sc-6131] Refresh configuration form once account changes are saved

app.babel, libs/common/src/assets/i18n/ca.json, libs/common/src/assets/i18n/en.json, libs/common/src/assets/i18n/es.json, libs/common/src/lib/select-account-kb/select-account/select-account.component.ts, libs/common/src/lib/select-account-kb/select-kb/select-kb.component.html, libs/common/src/lib/select-account-kb/select-kb/select-kb.component.ts, libs/common/src/lib/select-account-kb/utils.ts
- Remove `Back to accounts` button from the footer, as we have already a `Back` button in the header
- Fix Back behavior to display the list of accounts properly (was probably broken when we upgraded to ng16)
- Fix KB creation form from kb selection footer:
- hide "create kb" button once we click on it
- always enable cancel button
- disabled the form during creation to prevent multiple clicks while creation is in progress
- add error toast if creation fails
=> [sc-6469]: Fix back to accounts button

apps/dashboard/src/app/account/account-kbs/account-kbs.component.html, apps/dashboard/src/app/account/account-nua/account-nua.component.html
cypress-xpath package is deprecated, so we need to remove it from our cypress deps. To do so we need a way to access easily the NUA key and KB deletion buttons.
=> Add data-cy allowing to get rid of cypress-xpath

libs/common/src/lib/resources/edit-resource/profile/profile.component.html, libs/common/src/lib/resources/edit-resource/profile/profile.component.ts
We already have the footer’s button being disabled when the form was invalid or pristine, but disabling the form by default and enabling it after getting the data was marking the form as touched, and so enabling the footer’s buttons. So now, instead of disabling the form we hide it until we get the data to fill it.
=> [sc-7162]: prevent save & cancel buttons to be enabled by default

libs/common/src/lib/resources/resource-list/resource-list.component.ts
We used to refresh the resource list when `this.sdk.refreshing` event was triggered, but since the refactoring we made on resource list this call is redundant and was duplicating the first page of result when there were several pages.
=> Fix [sc-7197]: prevent loading resources twice

apps/dashboard/src/app/account/account-kbs/account-kbs.component.html, apps/dashboard/src/app/account/account-manage/account-manage.component.html, apps/dashboard/src/app/account/account-manage/account-manage.component.scss, apps/dashboard/src/app/account/account-nua/account-nua.component.html, apps/dashboard/src/app/account/account-users/account-users.component.html, apps/dashboard/src/app/activity/activity-download.component.html, apps/dashboard/src/app/knowledge-box/knowledge-box-keys/knowledge-box-keys.component.html, apps/dashboard/src/app/knowledge-box/knowledge-box-training/knowledge-box-training.component.html, apps/dashboard/src/app/knowledge-box/knowledge-box-training/training-history/training-history.component.html, libs/common/src/assets/i18n/ca.json, libs/common/src/assets/i18n/en.json, libs/common/src/assets/i18n/es.json, libs/common/src/assets/i18n/fr.json, libs/common/src/lib/knowledge-box-settings/knowledge-box-settings.component.html, libs/common/src/lib/widgets/widget-generator.component.html
and improve account management page:
- move zone field in the Manage account form and make it readonly
- delete account settings section
- update page name in the navbar to be "Account management" instead of "Account preferences"
=> [sc-7168] Unify titles in dashboard pages

libs/common/src/lib/resources/resource-list/resource-list.component.html, libs/common/src/lib/resources/resource-list/resource-list.component.ts, libs/common/src/lib/upload/upload-data/upload-data.component.html, libs/common/src/lib/upload/upload-data/upload-data.component.scss, libs/common/src/lib/upload/upload-data/upload-data.component.ts, libs/common/src/lib/utils/desktop.ts
- Fix no dataset import on empty monolingual: monolingual KB doesn't support dataset import, but they should display a message when they are empty
- Move `openDesktop` function from resource-list to `utils/desktop.ts`
- Back to only one NucliaDesktop button in Upload data page
=> [sc-7111] Improve upload data page

libs/common/src/lib/label/label-field/label-field.component.html, libs/common/src/lib/label/label-field/label-field.component.ts, libs/common/src/lib/label/labels.service.ts, libs/common/src/lib/resources/edit-resource/classification/paragraph-classification/paragraph-classification.component.ts, libs/common/src/lib/resources/edit-resource/classification/resource-classification.component.html, libs/common/src/lib/resources/edit-resource/classification/resource-classification.component.ts, libs/common/src/lib/resources/resource-list/error-resources-table/error-resources-table.component.spec.ts, libs/common/src/lib/resources/resource-list/pending-resources-table/pending-resources-table.component.spec.ts, libs/common/src/lib/resources/resource-list/processed-resource-table/processed-resource-table.component.spec.ts, libs/common/src/lib/resources/resource-list/resource-list.component.spec.ts, libs/common/src/lib/resources/resource-list/resource-list.service.ts
- add missing mark for check
- add isReady subject to resource classification page
- refactor labelField component to return hasLabel instead of noLabel
- refactor LabelsService replacing `getLabelsByKind` method by two properties: `resourceLabelSets` and `paragraphLabelSets` which emit only when labelSet is not null
- Fix tests (prevent error to be triggered and logged during unit tests)
=> Fix resource classification loading

apps/desktop/electron/src/service/nuclia-cloud.ts, package.json
the fix is not as ambitious as the story, it does not show any small icon next to the failing connector in the UI, but at least the server does not crash and the user can see a proper error message in the activity log
=> do not break if kb cannot be accessed

libs/common/src/lib/resources/edit-resource/classification/classification.helpers.ts, libs/common/src/lib/resources/edit-resource/classification/labels-expander/labels-expander.component.html, libs/common/src/lib/resources/edit-resource/classification/labels-expander/labels-expander.component.ts, libs/common/src/lib/resources/edit-resource/classification/paragraph-classification/paragraph-classification.component.ts, libs/common/src/lib/resources/edit-resource/classification/resource-classification.component.ts
- Fix resource classification page when no labels
- When there is label set for resources, the information message was missing
- When there are label set for resources but no label already on the resource, the warning saying "There is no label set for resources. You can add some in Classification page" was displayed on top of the label expander
- Do not allow to set more than one label when "multiple" is false
=> [sc-7554] don't set more than one label when multiple is false

libs/search-widget/src/common/checkbox/Checkbox.scss, libs/search-widget/src/common/checkbox/Checkbox.svelte, libs/search-widget/src/components/labels-expander/LabelsExpander.svelte
- When the user selects a labelset filter, all label that belong to this labelset are automatically deselected and disabled
- Avoid id collision in the checkbox component
=> [sc-7705] Disable label filters when a labelset is selected

libs/sdk-core/src/lib/db/search/chat.models.ts, libs/sdk-core/src/lib/db/search/chat.ts, libs/search-widget/src/core/api.ts, libs/search-widget/src/widgets/search-widget/SearchBar.svelte
- Allow multiple buttons to open the widget
- Include semantic search when calling the `chat` endpoint
=> [sc-7867] Search widget broken on nuclia com

apps/search-widget-demo/src/App.svelte, libs/sdk-core/src/lib/db/search/search.ts, libs/search-widget/src/core/api.ts, libs/search-widget/src/widgets/search-widget/SearchBar.svelte
- Fix [sc-7932]: keep clean default option in widget api
- Prevent bad features to be requested when using with_synonyms
- Fix App.svelte
=> [sc-7932] use synonyms option don't reset in widget generator

apps/dashboard/src/app/knowledge-box/knowledge-box-home/knowledge-box-home.component.ts
SDK `currentAccount` and `currentKb` are already `BehaviorSubject` and `ReplaySubject` so we don't need to use `shareReplay` on top of that.
Now copy button is working properly whenever we switch KB.
=> Fix [sc-8060]: no need for shareReplay on home page

libs/common/src/lib/resources/resource-list/error-resources-table/error-resources-table.component.html, libs/common/src/lib/resources/resource-list/pending-resources-table/pending-resources-table.component.html, libs/common/src/lib/resources/resource-list/processed-resource-table/processed-resource-table.component.html, libs/common/src/lib/resources/resource-list/resources-table.component.scss, libs/common/src/lib/resources/resource-list/resources-table.directive.ts, libs/common/src/lib/resources/resource-list/title-cell/title-cell.component.html, libs/common/src/lib/resources/resource-list/title-cell/title-cell.component.scss, libs/common/src/lib/resources/resource-list/title-cell/title-cell.component.ts, libs/common/src/lib/resources/resources.module.ts
In resource list, we created a new `title-cell` component because all the resource tables (processed, pending and error) are sharing the same code for the title cell.
Now the resource title is a real link (but we kept the same style, except it is underlined on hover), so we can easily open it on a new tab. Clicking anywhere else on the title cell is still navigating to the resource on the same tab as it used to.
We took the opportunity to use new Angular control flow in resource list components.
=> [sc-8106] render the resource title as a link in resources

apps/dashboard/src/app/app-routing.module.ts, apps/dashboard/src/app/app-title.strategy.ts, apps/dashboard/src/app/app.component.ts, apps/dashboard/src/app/app.module.ts, apps/dashboard/src/app/knowledge-box/knowledge-box-home/kb-metrics/kb-metrics.component.scss, apps/nucliadb-admin/src/app/app-routing.ts, apps/nucliadb-admin/src/app/app-title.strategy.ts, apps/nucliadb-admin/src/app/app.component.ts, apps/nucliadb-admin/src/app/app.module.ts, libs/common/src/lib/guards/index.ts, libs/common/src/lib/guards/set-account.guard.ts, libs/common/src/lib/guards/set-kb.guard.ts, libs/common/src/lib/guards/set-local-kb.guard.ts, libs/common/src/lib/resources/resource-list/resource-list.component.spec.ts, libs/common/src/lib/select-account-kb/select-account/select-account.component.ts, libs/common/src/lib/select-account-kb/select-kb/select-kb.component.scss, libs/core/src/lib/api/sdk.service.ts
- Use proper title strategy on Dashboard and NucliaDB admin apps
- Move `updateStateOnRouteChange` logic in new guards
- Keep only tracking navigation logic in `app.component`, and remove `updateStateOnRouteChange` method
- Create two new guards for dashboard: `setAccountGuard` and `setKbGuard` allowing to set the current account and KB while navigating through the app
- Create a new guard `setLocalKbGuard` for NucliaDB admin
- Some style improvements
=> [sc-8176] simplify updateStateOnRouteChange in dashboard and NucliaDB admin

apps/search-widget-demo/src/App.svelte, libs/search-widget/src/common/modal/Modal.scss, libs/search-widget/src/widgets/search-widget/SearchBar.scss, libs/search-widget/src/widgets/search-widget/SearchBar.svelte, libs/search-widget/src/widgets/search-widget/SearchResults.scss, libs/search-widget/src/widgets/search-widget/SearchResults.svelte
Move relations out of the search results layout and display them in a modal instead, which is displayed when clicking on an info button next to the search bar.
=> [sc-8270] Display relations in a modal

libs/sdk-core/README.md
A quick fix I came across while browsing the docs. If I'm not mistaken, this file is what ends up being rendered to: https://docs.nuclia.dev/docs/guides/sdk/js-sdk/
=> Update documentation link

libs/common/src/lib/kb-add/kb-add.component.html, libs/common/src/lib/kb-add/kb-add.component.ts, libs/common/src/lib/kb-add/kb-add.module.ts, libs/common/src/lib/knowledge-box-settings/knowledge-box-settings.service.ts, libs/common/src/lib/select-account-kb/select-kb/select-kb.component.scss, libs/core/src/lib/models/index.ts, libs/core/src/lib/models/kb.models.ts, libs/core/src/lib/utils/utils.ts, libs/user/src/lib/index.ts, libs/user/src/lib/onboarding/language-field/language-field.component.html, libs/user/src/lib/onboarding/language-field/language-field.component.scss, libs/user/src/lib/onboarding/language-field/language-field.component.ts, libs/user/src/lib/onboarding/onboarding.component.ts, libs/user/src/lib/onboarding/onboarding.models.ts, libs/user/src/lib/onboarding/onboarding.service.ts, libs/user/src/lib/onboarding/step2/step2.component.html, libs/user/src/lib/onboarding/step2/step2.component.scss, libs/user/src/lib/onboarding/step2/step2.component.ts, libs/user/src/lib/user-container/user-container.component.scss
- Create a standalone component for language field in KB creation
- Move function allowing to get KB configuration from backend configuration and user’s choices to the core lib.
- Update KB création dialog to use the new language-field component
- Fix KB creation from onboarding by passing account id instead of account slug (have been broken during SDK clean up)
=> [sc-8274] consistent language model on KB creation

libs/common/src/lib/notifications/notification.service.ts, libs/common/src/lib/notifications/notifications-panel/notifications-panel.component.ts, libs/sdk-core/CHANGELOG.md, libs/sdk-core/package.json, libs/sdk-core/src/lib/db/kb/kb.models.ts, libs/sdk-core/src/lib/db/kb/kb.ts
- Add `listenToResourceOperationNotifications` method which is sending notifications about resource creation, modification and deletion.
- Update `listenToProcessingNotifications` documentation to clarify that notifications are sent anytime processing is done, which occurs for both resource creation and modification.
=> [sc-8764] Add listenToResourceOperationNotifications method

libs/common/src/lib/ai-models/ai-models.component.html, libs/common/src/lib/ai-models/ai-models.component.scss, libs/common/src/lib/prompt-lab/prompt-lab.component.html
Also increase radio-group max-height for models to stay displayed on two columns (we added quite a lot of models lately)
=> Prevent sanitizing chevrons from prompts

apps/dashboard/src/app/account/billing/subscriptions/aws-subscription/aws-subscription.component.ts, apps/dashboard/src/app/account/billing/usage/budget.component.html, apps/dashboard/src/app/account/billing/usage/budget.component.ts, apps/dashboard/src/app/onboarding/aws-onboarding/aws-onboarding.component.ts, libs/common/src/lib/knowledge-box-settings/knowledge-box-settings.component.html, libs/core/src/lib/api/billing.service.ts, libs/core/src/lib/api/sdk.service.ts, libs/core/src/lib/api/zone.service.ts, libs/core/src/lib/models/billing.model.ts, libs/user/src/lib/onboarding/onboarding.component.ts
- Fix `getZones` method
- return all zones when there is no account (regular onboarding)
- return all zones when there is an error while get the account subscription
- return all zones when the subscription is not AWS
- return only AWS zones when subscription is AWS and the environment is not dev or stage.
- Fix subscription update for AWS
- [sc-9199]: Separate AWS model properties from StripeAccountSubscription
=> [sc-9223] display only aws zones on aws accounts

libs/common/common.babel, libs/common/src/assets/i18n/ca.json, libs/common/src/assets/i18n/en.json, libs/common/src/assets/i18n/es.json, libs/common/src/assets/i18n/fr.json, libs/common/src/lib/knowledge-box-settings/knowledge-box-settings.component.html, libs/common/src/lib/knowledge-box-settings/knowledge-box-settings.component.ts, libs/sdk-core/CHANGELOG.md, libs/sdk-core/src/lib/db/kb/kb.models.ts
The frontend is fully ready, but resetting the field doesn't work yet (Core services team is aware and working on a fix)
=> [sc-9361] Add management of allowed CORS domains in KB settings page

apps/dashboard/src/app/knowledge-box/knowledge-box-home/knowledge-box-home.component.html, apps/dashboard/src/app/knowledge-box/knowledge-box-home/knowledge-box-home.component.spec.ts, apps/dashboard/src/app/knowledge-box/knowledge-box-home/knowledge-box-home.component.ts, libs/common/common.babel, libs/common/src/assets/i18n/ca.json, libs/common/src/assets/i18n/en.json, libs/common/src/assets/i18n/es.json, libs/common/src/assets/i18n/fr.json
In the dashboard home page, we removed the KB slug, and we added the KB region in the KB details block.
=> [sc-9515]: Replace slug by region in KB details

libs/common/common.babel, libs/common/src/assets/i18n/ca.json, libs/common/src/assets/i18n/en.json, libs/common/src/assets/i18n/es.json, libs/common/src/assets/i18n/fr.json, libs/common/src/lib/ai-models/answer-generation/answer-generation.component.html, libs/common/src/lib/ai-models/answer-generation/answer-generation.component.ts, libs/common/src/lib/widgets/widget-generator.component.html, libs/common/src/lib/widgets/widget-generator.component.ts, libs/core/src/lib/label/label-sets/label-set/label-set-form/label-set-form.component.scss, mrs.developer.json, package.json, yarn.lock
- Display popover help on chatGPT-vision in AI models
- Use new pastanaga version and adapt label set form to the new look and feel of radios
- Add popover help for chatGPT-vision in generative answer section of AI models page
- Enable image options by default for vision models
- Disable image options for models not supporting vision
=> [sc-9587] openai vision image recognition model integration

libs/common/src/lib/tasks-automation/task-forms/labeling-configuration/labeling-configuration.component.ts, libs/core/src/lib/label/label-sets/label-set/label-set-form/label-set-form-modal.component.html, libs/core/src/lib/label/label-sets/label-set/label-set-form/label-set-form-modal.component.ts, libs/core/src/lib/label/label-sets/label-set/label-set-form/label-set-form.component.html, libs/core/src/lib/label/label-sets/label-set/label-set-form/label-set-form.component.ts, libs/sync/src/lib/configuration-form/configuration-form.component.ts, libs/sync/src/lib/sync-details-page/sync-settings/sync-settings.component.html
- Don't display label set kind radio group in label set creation modal on sync and task creation forms (as there is only one possible kind to be chosen for those cases)
- Don't display security groups toggle in sync details when the corresponding connector doesn't have `canSyncSecurityGroups: true`
=> [sc-9421] new sync page fixes

apps/nucliadb-admin/src/app/app.module.ts
It seems that `DateTimeService` depends on the `TranslatePipe`.
To fulfill this dependency, `PaTranslateModule` is imported in the root module.
=> [sc-10704] Fix widget page in NucliaDB admin

.github/workflows/deploy.yml, apps/dashboard/src/app/app.module.ts
This is to prevent deployment to fail when the commit sha starts with a `0`.
> The problem here is versioning of the charts, where if metadata (the part after +) starts with 0 is not matched with the correct version of a chart in the registry (that being said, version metadata are not used for version comparison by design in semver v2).
> In your pipelines, a hack fix could be changing this to something like ```echo "SHORT_SHA=`echo hash${GITHUB_SHA} | cut -c1-12`" >> $GITHUB_ENV```. That would make metadata (the git hash currently) being prepended with "hash" and hence getting around this problem.
=> Add hash in commit version

apps/dashboard/src/app/onboarding/getting-started/getting-started.component.ts, apps/dashboard/src/app/onboarding/getting-started/upload-list/upload-list.component.html, libs/common/src/assets/i18n/ca.json, libs/common/src/assets/i18n/en.json, libs/common/src/assets/i18n/es.json, libs/common/src/assets/i18n/fr.json
- Fix remaining time format
- When the backend doesn't return the remaining processing time, `1min` is displayed instead of `1s`
=> [sc-10860] Fix time format on getting started dialog

libs/core/src/lib/api/sdk.service.ts
- When switching to another user in the Dashboard, the `currentKb` observable is not always updated as expected, keeping the kb from the previous user. It's fixed by moving the `distinctUntilChanged` operator.
=> [sc-10922] Properly update current kb when switching to another user

libs/common/src/lib/metrics/metrics-page.component.html, libs/common/src/lib/metrics/metrics-page.component.scss, libs/common/src/lib/metrics/metrics-page.component.ts, libs/common/src/lib/metrics/missing-knowledge-details/missing-knowledge-details.component.html, libs/common/src/lib/metrics/missing-knowledge-details/missing-knowledge-details.component.ts, libs/common/src/lib/metrics/remi-metrics.service.ts, libs/common/src/lib/resources/edit-resource/edit-resource.module.ts, libs/common/src/lib/resources/edit-resource/index.ts, libs/common/src/lib/resources/edit-resource/preview/index.ts, libs/common/src/lib/resources/edit-resource/preview/preview.component.ts, libs/common/src/lib/resources/edit-resource/preview/preview.service.ts, libs/sdk-core/CHANGELOG.md, libs/sdk-core/src/lib/db/kb/activity/remi.models.ts, libs/sdk-core/src/lib/db/resource/resource.mapper.ts
- Fix gap between missing knowledge section and the criteria expanders appearing on scroll
- Don't display scores columns on missing answers details table
- Open viewer from missing knowledge context (opens only the corresponding resource/field for now)
=> [sc-10931] REMi metrics open context in the viewer

apps/dashboard/src/app/app-routing.module.ts, apps/dashboard/src/app/knowledge-box/knowledge-box-users/users-manage/users-manage.component.html, apps/dashboard/src/app/knowledge-box/knowledge-box-users/users-manage/users-manage.component.ts, apps/dashboard/src/app/knowledge-box/knowledge-box-users/users-manage/users-manage.service.ts, libs/common/src/lib/navbar/navbar.component.html, libs/common/src/lib/navbar/navbar.component.ts, libs/sdk-core/CHANGELOG.md, libs/sdk-core/package.json, libs/sdk-core/src/lib/db/kb/kb.ts
- display user menu in the navbar for KB owners
- use KB owners guard on KB users page
- Refactor `kb.getUsers` method to call only KB endpoint
- Clean up `users-manage` page
=> [sc-11003] User menu must be accessible for KB owners

.github/workflows/deploy.yml
This pull request includes changes to the deployment workflow in the `.github/workflows/deploy.yml` file, specifically replacing the `curl` command with `helm push` for uploading Helm charts. 
Deployment workflow updates:
* [`.github/workflows/deploy.yml`](diffhunk://#diff-28802fbf11c83a2eee09623fb192785e7ca92a3f40602a517c011b947a1822d3L232): Removed the `curl` command and replaced it with `helm push` for uploading the `app` Helm chart.
* [`.github/workflows/deploy.yml`](diffhunk://#diff-28802fbf11c83a2eee09623fb192785e7ca92a3f40602a517c011b947a1822d3L295): Removed the `curl` command and replaced it with `helm push` for uploading the `manager` Helm chart.
=> Don't push to chart museum

.github/workflows/deploy.yml
This pull request includes significant updates to the GitHub Actions workflow configuration in the `.github/workflows/deploy.yml` file. The changes aim to streamline the deployment process by introducing new steps and actions, as well as removing redundant ones.
Improvements and updates to the deployment workflow:
* **Environment Variable Updates:**
- Removed the `ARTIFACT_REGISTRY_URL` environment variable.
* **Job Configuration Changes:**
- Changed the runner from `ubuntu-latest` to `nuclia-base` for the `build` job.
* **New Actions and Steps:**
- Added steps to generate a GitHub App token and check out the tooling repository. [[1]](diffhunk://#diff-28802fbf11c83a2eee09623fb192785e7ca92a3f40602a517c011b947a1822d3L123-R148) [[2]](diffhunk://#diff-28802fbf11c83a2eee09623fb192785e7ca92a3f40 …
=> Use new docker build pipeline for image signing

.github/workflows/deploy.yml
This pull request includes a small change to the `.github/workflows/deploy.yml` file. The change adds two new secrets for the GitHub App configuration.
* `jobs:` section in `.github/workflows/deploy.yml`: Added `ghapp-nuclia-service-bot-id` and `ghapp-nuclia-service-bot-pk` secrets for the GitHub App configuration.
=> Add missing parameter when triggering second build image

.github/workflows/deploy.yml
This pull request includes changes to the deployment workflow configuration in the `.github/workflows/deploy.yml` file. The main change is the addition of the `aws-ecr-role` parameter to the job configurations to replace the `skip-ecr-push` parameter.
Changes in deployment workflow configuration:
* [`.github/workflows/deploy.yml`](diffhunk://#diff-28802fbf11c83a2eee09623fb192785e7ca92a3f40602a517c011b947a1822d3L168-R168): Replaced `skip-ecr-push: true` with `aws-ecr-role: ${{ secrets.AWS_ECR_ROLE }}` for the `docker/Dockerfile` job configuration.
* [`.github/workflows/deploy.yml`](diffhunk://#diff-28802fbf11c83a2eee09623fb192785e7ca92a3f40602a517c011b947a1822d3L195-R195): Replaced `skip-ecr-push: true` with `aws-ecr-role: ${{ secrets.AWS_ECR_ROLE }}` for the `docker/Dockerfile` job …
=> Push manager and app to ecr

apps/manager-v2/src/app/app.component.ts, charts/manager/templates/manager.cm.yaml
This pull request includes a small change to the `charts/manager/templates/manager.cm.yaml` file. The change ensures that the `NO_STRIPE` value is properly quoted.
* [`charts/manager/templates/manager.cm.yaml`](diffhunk://#diff-dbe807a14a4343ece07a9735f4cfbb9b80aa904c6cb81d4e39dcee2dab650f2dL18-R18): Quoted the `NO_STRIPE` value to ensure it is interpreted correctly.
=> manage: Quote boolean in chart

charts/app/templates/app.cm.yaml, charts/app/templates/app.deploy.yaml, charts/app/values.yaml, charts/manager/templates/manager.cm.yaml, charts/manager/templates/manager.deploy.yaml, charts/manager/values.yaml
This pull request updates the configuration management for `app` and `manager` Helm charts by standardizing the naming conventions for `ConfigMap` resources and introducing support for `envFrom` values. The changes improve clarity and flexibility in environment variable management.
* **Standardized ConfigMap naming**: Changed the `ConfigMap` name from `{{ .Release.Name }}-config` to `app-config` in `charts/app/templates/app.cm.yaml`.
* **Added `envFrom` support**: Introduced the ability to configure environment variables using `envFrom` in `charts/app/templates/app.deploy.yaml` and `charts/app/values.yaml`. [[1]](diffhunk://#diff-0720014cb417d58c8cbb5717d9aa6402e157855002fdb20373eea9f2677fd2f0R55-R58) [[2]](diffhunk://#diff-dfbca39ca13a7dd62bff1bd65a1ea1aa719d16eb5ccda48ef12a2eead0bf865fR7 …
=> charts: Parametrize envFrom

apps/dashboard/src/app/retrieval-agent/agent-dashboard/workflow/basic-elements/connectable-entry/connectable-entry.component.html, apps/dashboard/src/app/retrieval-agent/agent-dashboard/workflow/basic-elements/connectable-entry/connectable-entry.component.scss, apps/dashboard/src/app/retrieval-agent/agent-dashboard/workflow/basic-elements/connectable-entry/connectable-entry.component.ts, apps/dashboard/src/app/retrieval-agent/agent-dashboard/workflow/basic-elements/node.directive.ts, apps/dashboard/src/app/retrieval-agent/agent-dashboard/workflow/nodes/ask/ask-node.component.ts, apps/dashboard/src/app/retrieval-agent/agent-dashboard/workflow/nodes/internet/internet-form.component.ts, apps/dashboard/src/app/retrieval-agent/agent-dashboard/workflow/workflow.effects.ts, apps/dashboard/src/app/retrieval-agent/agent-dashboard/workflow/workflow.models.ts, apps/dashboard/src/app/retrieval-agent/agent-dashboard/workflow/workflow.service.ts, apps/dashboard/src/app/retrieval-agent/agent-dashboard/workflow/workflow.state.ts, libs/sdk-core/src/lib/db/retrieval-agent/retrieval-agent.models.ts
- Ask agent can have only one fallback node, disable fallback output when it already has a child link
- Update fallback link position when ask conffig is fully loaded (as it may change the box height)
- Properly save on backend when we delete fallback node from the UI
=> [sc-12121] arag fallback with one link constraint

apps/dashboard/src/app/app.component.ts, apps/manager-v2/src/app/app.component.ts, charts/app/templates/app.cm.yaml, charts/app/values.yaml, charts/manager/templates/manager.cm.yaml, charts/manager/values.yaml
This pull request refactors configuration management for sensitive data by removing `SITE_KEY` and `SENTRY_URL` from the Helm charts' `ConfigMap` and `values.yaml` files. These values are now intended to be managed as secrets, improving security practices. The changes affect both the `app` and `manager` charts.
* [`charts/app/templates/app.cm.yaml`](diffhunk://#diff-26ed6a864e2f47f08cb34f34fc86184c2b6d90c777f9200bc1202d57b906d5fbL12-L20): Removed `SITE_KEY` and `SENTRY_URL` from the `ConfigMap` definition.
* [`charts/app/values.yaml`](diffhunk://#diff-dfbca39ca13a7dd62bff1bd65a1ea1aa719d16eb5ccda48ef12a2eead0bf865fL21-L29): Removed `site_key` and `sentry_url` from the `values.yaml` file. Added comments indicating these values should be managed as secrets. …
=> charts: Remove secrets from ConfigMap

libs/core/src/lib/api/sdk.service.ts, libs/core/src/lib/services/navigation.service.ts
From [combineLatest documentation](https://www.learnrxjs.io/learn-rxjs/operators/combination/combinelatest):
> `combineLatest` will not emit an initial value until each observable emits at least one value
`currentArag` is from a ReplaySubject, so it's not emitting until the user select an agent, while `arag` is from a behavior subject.
=> Fix homeUrl: make sure clicking on nuclia logo always works

libs/common/src/lib/retrieval-agent/agent-dashboard/workflow/nodes/ask/ask-form.component.ts, libs/common/src/lib/retrieval-agent/agent-dashboard/workflow/nodes/cypher/cypher-form.component.ts, libs/common/src/lib/retrieval-agent/agent-dashboard/workflow/nodes/cypher/cypher-node.component.ts, libs/common/src/lib/retrieval-agent/agent-dashboard/workflow/nodes/guardrails/guardrails-form.component.ts, libs/common/src/lib/retrieval-agent/agent-dashboard/workflow/nodes/internet/internet-form.component.ts, libs/common/src/lib/retrieval-agent/agent-dashboard/workflow/nodes/mcp/mcp-form.component.html, libs/common/src/lib/retrieval-agent/agent-dashboard/workflow/nodes/mcp/mcp-node.component.ts, libs/common/src/lib/retrieval-agent/agent-dashboard/workflow/nodes/rephrase/rephrase-form.component.ts, libs/common/src/lib/retrieval-agent/agent-dashboard/workflow/nodes/sql/sql-form.component.ts, libs/common/src/lib/retrieval-agent/agent-dashboard/workflow/nodes/sql/sql-node.component.ts, libs/common/src/lib/retrieval-agent/agent-dashboard/workflow/sidebar/test-agent/test-panel.component.html, libs/common/src/lib/retrieval-agent/agent-dashboard/workflow/sidebar/test-agent/test-panel.component.ts, libs/common/src/lib/retrieval-agent/agent-dashboard/workflow/sidebar/test-agent/test-panel.service.ts, libs/common/src/lib/retrieval-agent/drivers/drivers-page.component.html, libs/common/src/lib/retrieval-agent/drivers/drivers-page.component.ts, libs/sdk-core/src/lib/db/retrieval-agent/driver.models.ts, libs/sdk-core/src/lib/db/retrieval-agent/index.ts, libs/sdk-core/src/lib/db/retrieval-agent/interactions.models.ts, libs/sdk-core/src/lib/db/retrieval-agent/retrieval-agent.models.ts, libs/sdk-core/src/lib/db/retrieval-agent/retrieval-agent.ts, libs/sdk-core/src/lib/db/retrieval-agent/retrieval-agent.types.ts, libs/sdk-core/src/lib/rest/rest.ts, yarn.lock
- Properly send messages to the WebSocket (we can now see the message sent in the network tab)
- Fix the drivers model to follow Ramon's changes:
- `id` property will be removed (no more id generated by backend)
- `identifier` must be provided by the front (backend create the full workflow in one snapshot) and it's this identifier which must be used as a source in agents
=> [sc-12307] retrieval agent test and interactions 4

.github/workflows/deploy.yml, apps/dashboard/src/app/app.component.ts, libs/search-widget/src/widgets/search-widget/SearchBar.svelte
This pull request updates the deployment workflow in `.github/workflows/deploy.yml` to include a new step for invalidating the CDN cache when deploying to the main branch.
* Added a new step, "Invalidate CDN cache stage," to invalidate the CDN cache using the `gcloud compute url-maps invalidate-cdn-cache` command. This step is conditionally executed when either the widget or SDK is deployed and the branch is `main`.
=> Invalidate cache once CDN sync happens

libs/sdk-core/src/lib/db/resource/resource.ts
The filtering by id wasn't working properly because the parameter name was not correct
=> Fix: Send run-agents ids in `agent_ids`  instead of `agents_ids`
