app.babel, apps/app/src/app/resources/resource-list.component.html, apps/app/src/app/resources/resource-list.component.ts, libs/common/src/assets/i18n/ca.json, libs/common/src/assets/i18n/en.json, libs/common/src/assets/i18n/es.json, libs/core/src/lib/utils.ts, libs/sdk-core/src/lib/db/index.ts, libs/sdk-core/src/lib/db/resource.mapper.ts, libs/sdk-core/src/lib/db/resource.ts
Adding an option to download Algolia JSON from the resource list
=> Be able to download a Json file from a document [sc-1649]

apps/dashboard/src/app/app-routing.module.ts, apps/dashboard/src/app/components/stash-navbar/stash-navbar.component.html, apps/dashboard/src/app/components/topbar/topbar.component.ts, apps/dashboard/src/app/knowledge-box/knowledge-box-users/users-manage/users-manage.component.html, apps/dashboard/src/app/knowledge-box/knowledge-box-users/users-manage/users-manage.component.ts, libs/search-widget/src/core/api.ts
- In the resource viewer, the option "Show API endpoint" should be visible to all roles.
- Only account owners should be able to manage KB users.
- Account owners should be able to change their own role in a KB.
=> Oriolperramon8396/sc 2063/fix permission issues

apps/search-widget-demo/src/App.svelte, libs/search-widget/src/widgets/FormWidget.svelte, libs/search-widget/src/widgets/results/Results.svelte, libs/search-widget/src/widgets/row/Row.svelte, libs/search-widget/src/widgets/search-input/SearchInput.svelte
- hide "search in title option"
- keep the results full screen but make the input smaller (448px) and centered
- hide the date in the results for form widget
=> [sc-2071]: Improve form widget for Rust conf

apps/dashboard/src/app/resources/edit/edit-resource.component.scss, apps/dashboard/src/app/resources/edit/edit-resource.component.ts, apps/dashboard/src/app/resources/edit/profile/profile.component.html, apps/dashboard/src/app/resources/edit/profile/profile.component.ts, apps/dashboard/src/app/resources/resources.module.ts, apps/sistema-demo/src/app/app.component.ts, mrs.developer.json
- Add ability to choose the thumbnail when there are several of them
- Add radio button documentation in sistema-demo
=> [sc-2011] Add ability to choose the thumbnail when there are several of them

libs/sdk-core/src/lib/db/resource.mapper.ts, libs/search-widget/public/i18n/ca.json, libs/search-widget/public/i18n/en.json, libs/search-widget/public/i18n/es.json, libs/search-widget/public/i18n/fr.json, libs/search-widget/src/viewer/Metadata.svelte, libs/search-widget/src/widgets/row/Row.svelte, libs/search-widget/src/widgets/row/Square.svelte
- Replace "user_metadata" property
- Show labels in resource viewer
=> Oriolperramon8396/sc 2079/labels of resources are not displayed properly

apps/dashboard/src/app/ontologies/ontologies.component.html, apps/dashboard/src/app/ontologies/ontologies.module.ts, apps/dashboard/src/app/ontologies/ontology/ontology.component.html, apps/dashboard/src/app/ontologies/ontology/ontology.component.scss, apps/dashboard/src/app/ontologies/ontology/ontology.component.ts, apps/dashboard/src/app/resources/edit/edit-resource.component.scss
- Fix [sc-2045]: don't repeat delete and save label requests
-  Use Pastanaga components in Ontology component (label set creation/edition page)
=> Fix [sc-2045]: don't repeat delete and save label requests

app.babel, apps/dashboard/src/app/widgets/edit/edit-widget.component.html, apps/dashboard/src/app/widgets/edit/edit-widget.component.ts, apps/search-widget-demo/src/App.svelte, libs/common/src/assets/i18n/en.json, libs/sdk-core/src/lib/db/kb.models.ts, libs/search-widget/src/widget.svelte, libs/search-widget/src/widgets/FormWidget.svelte, libs/search-widget/src/widgets/InputWidget.svelte, libs/search-widget/src/widgets/search-input/SearchInput.svelte
- Add placeholder option to the widget in both input and form modes (even though the placeholder is not visible on input mode)
- Add placeholder field in widget edition form
=> Fix [sc-2080]: Add ability to customize the widget placeholder for form and input

libs/search-widget/src/core/api.ts, libs/search-widget/src/core/tensor.ts, libs/search-widget/src/widgets/suggestions/Suggestions.svelte
Add auth headers when getting private KB models
=> Add auth headers when getting private KB models

libs/search-widget/src/components/icons/search.svelte, libs/search-widget/src/components/spinner/Spinner.svelte, libs/search-widget/src/widgets/FormWidget.svelte
- Fix spinner and lens icon
- Add suggestions to Form widget
=> [sc-2092] Fix spinner in input widget

apps/dashboard/src/app/select/select.component.scss, apps/desktop/src/app/connectors/connector/connector.component.html, apps/desktop/src/app/connectors/connector/connector.component.scss, apps/desktop/src/app/connectors/connector/connector.component.ts, apps/desktop/src/app/connectors/connectors.component.html, apps/desktop/src/app/connectors/connectors.component.scss, apps/desktop/src/app/connectors/connectors.component.spec.ts, apps/desktop/src/app/connectors/connectors.component.ts, apps/desktop/src/app/connectors/connectors.module.ts, apps/desktop/src/app/sync/destinations/algolia.ts, apps/desktop/src/app/sync/destinations/nuclia-cloud.ts, apps/desktop/src/app/sync/models.ts, apps/desktop/src/assets/i18n/ca.json, apps/desktop/src/assets/i18n/en.json, apps/desktop/src/assets/i18n/es.json, apps/desktop/src/assets/i18n/fr.json, desktop.babel
- Add refresh button for nuclia cloud destination
-  Display connector list and fields on the same page, allowing to change the destination chosen without having to go back
=> [sc-2029] Add refresh button for nuclia cloud destination

app.babel, apps/dashboard/src/_variables.scss, apps/dashboard/src/app/account/account.component.html, apps/dashboard/src/app/components/stash-navbar/stash-navbar.component.html, apps/dashboard/src/app/components/stash-navbar/stash-navbar.component.scss, apps/dashboard/src/app/knowledge-box/knowledge-box-home/knowledge-box-home.component.html, apps/dashboard/src/app/knowledge-box/knowledge-box-home/knowledge-box-home.component.scss, apps/dashboard/src/app/knowledge-box/knowledge-box-home/knowledge-box-home.component.spec.ts, apps/dashboard/src/app/knowledge-box/knowledge-box-home/knowledge-box-home.component.ts, libs/common/src/assets/i18n/ca.json, libs/common/src/assets/i18n/en.json, libs/common/src/assets/i18n/es.json, libs/sistema/styles/_mixins.scss, libs/sistema/styles/_variables.scss, libs/sistema/theme/tokens/_palette.tokens.scss
-  use pa-icons and improve stash-navbar following new design
-  new dark-mode mixin
-  refactor kb home with Pastanaga
=> [sc-1837] use sistema icons in navbar + kb home refactoring

libs/search-widget/src/core/models.ts, libs/search-widget/src/core/store.ts, libs/search-widget/src/core/tensor.ts, libs/search-widget/src/widgets/suggestions/Suggestions.svelte
Fix label intent according new format
=> [sc-2097] Fix label intent according new format

apps/dashboard/src/app/account/account-users/account-users.component.html, apps/dashboard/src/app/account/account-users/account-users.component.ts, apps/dashboard/src/app/account/account.module.ts, libs/sistema/src/lib/dropdown-button/dropdown-button.component.html, libs/sistema/src/lib/dropdown-button/dropdown-button.component.ts, mrs.developer.json
-  don't keep new role when not confirmed
- prevent ExpressionChangedAfterItHasBeenCheckedError by replacing old STF-select and its 2 way data-binding by a dropdown-button with one way data-binding
=> Fix changing user's account role [sc-2112] 

apps/dashboard/src/app/knowledge-box/knowledge-box/knowledge-box.component.ts, apps/dashboard/src/app/services/app.service.ts, apps/dashboard/src/app/setup/setup-account/setup-account.component.html, apps/dashboard/src/app/setup/setup-account/setup-account.component.scss, apps/dashboard/src/app/setup/setup-account/setup-account.component.ts, apps/dashboard/src/app/setup/setup.module.ts, libs/sistema/theme/tokens/_textfield.tokens.scss
- open demo in a new tab
- display the empty kb alert only on the right kb
=> [sc-2110] onboarding open demo kb in another tab

libs/search-widget/src/widgets/row/Row.svelte, libs/search-widget/src/widgets/row/Square.svelte, libs/search-widget/src/widgets/row/Thumbnail.svelte
- Create a thumbnail component to be used everywhere a thumbnail is displayed.
=> [sc-2121] Create a thumbnail component

.github/workflows/deploy.yml, apps/search-widget-demo/src/App.svelte, libs/search-widget/src/SearchBar.svelte, libs/search-widget/src/Widget.svelte, libs/search-widget/src/css-variables.css, libs/search-widget/src/widgets/EmbeddedSearch.svelte, libs/search-widget/src/widgets/search-input/SearchInput.svelte
-  Fix suggestion box-shadow and width [sc-2140]
- Force demo widgets to be in english
- Deploy all the files from search-widget/public folder
=> Fix suggestion box-shadow and width [sc-2140]

apps/search-widget-demo/src/App.svelte, libs/search-widget/src/SearchBar.svelte, libs/search-widget/src/Widget.svelte, libs/search-widget/src/core/search-bar.ts, libs/search-widget/src/widgets/search-input/SearchInput.svelte
- Trigger suggestion between each word
- Trigger suggestion after 500ms of inactivity when trimmed query changed
=> [sc-2136] avoid unnecessary suggest calls

libs/search-widget/src/SearchBar.svelte, libs/search-widget/src/SearchResults.svelte, libs/search-widget/src/Widget.svelte, libs/search-widget/src/core/utils.ts
Solution inspired by https://dev.to/akdevcraft/use-font-in-web-component-51a4 and https://medium.com/codex/using-fonts-in-web-components-6aba251ed4e5
=> Fix [sc-2138]: Load fonts for the widgets

apps/search-widget-demo/src/App.svelte, libs/search-widget/src/_video-widget/Icon.svelte, libs/search-widget/src/_video-widget/VideoTile.svelte
- Fix side panel height on big screens
- Prevent undefined in class list
=> [sc-2194] video tile fixes

libs/search-widget/src/_video-widget/ThumbnailPlayer.svelte, libs/search-widget/src/_video-widget/VideoTile.svelte, libs/search-widget/src/widgets/row/Thumbnail.svelte
- Fix "Show all results" transition on mobile
- Thumbnail player fade in transition
=> [sc-2195] Thumbnail player fade in

libs/search-widget/src/_video-widget/SearchResults.svelte, libs/search-widget/src/_video-widget/VideoTile.svelte, libs/search-widget/src/components/spinner/LoadingDots.svelte, libs/search-widget/src/components/spinner/Spinner.svelte, libs/search-widget/src/widgets/results/Results.svelte, libs/search-widget/src/widgets/search-input/SearchInput.svelte, libs/sistema/src/lib/progress/spinner/spinner.component.scss
* Add real spinner and use it while loading the video
* Scroll to display the expanded tile when needed
* Rename Spinner into LoadingDots
* Remove bad transitions
* Fix gaps
=> [sc-2195] video tile animation and transitions

libs/search-widget/src/Widget.scss, libs/search-widget/src/Widget.svelte, libs/search-widget/src/_video-widget/SearchBar.svelte, libs/search-widget/src/_video-widget/SearchResults.scss, libs/search-widget/src/_video-widget/SearchResults.svelte, libs/search-widget/src/_video-widget/VideoTile.scss, libs/search-widget/src/_video-widget/VideoTile.svelte, libs/search-widget/src/common-style.scss, libs/search-widget/src/core/utils.ts
- Keep paragraphs centered when there is only a few of them
- Load CSS variables through SCSS
=> [sc-2242] better css strategy

apps/search-widget-demo/src/App.svelte, libs/search-widget/src/_video-widget/ThumbnailPlayer.scss, libs/search-widget/src/_video-widget/ThumbnailPlayer.svelte, libs/search-widget/src/_video-widget/VideoTile.scss, libs/search-widget/src/_video-widget/VideoTile.svelte, libs/search-widget/src/common-style.scss
* Allow to hide configuration in the demo
* Video tile template refactoring
- Better support window resizing
- New breakpoints fine-tuning the layout
- Display only the main summary
- Better management of tile size
* Enable aspect ratio setup on thumbnail player
* Make transcripts acting like an accordion
=> [sc-2262] Video tile animation v2

libs/search-widget/src/_video-widget/VideoTile.svelte, libs/search-widget/src/components/button/Button.scss, libs/search-widget/src/components/button/CloseButton.svelte, libs/search-widget/src/viewer/Entities.svelte
* VideoTile: Fix play from paragraph buttons
* Fix close button style
* Don't trigger search when annotation mode is enabled
=> [sc-2409] fixes

libs/search-widget/src/viewer/Metadata.svelte, libs/search-widget/src/viewer/paragraphs/ParagraphWithAnnotations.svelte
- Annotation mode off when closing viewer
- Fix text selection on Chrome/Safari
=> Fix text selection on Chrome/Safari

libs/search-widget/src/core/api.ts, libs/search-widget/src/core/models.ts, libs/search-widget/src/viewer/menus/LabelMenu.svelte, libs/search-widget/src/viewer/paragraphs/Paragraph.svelte, libs/search-widget/src/viewer/paragraphs/ParagraphWithIcon.svelte, libs/search-widget/src/viewer/paragraphs/ParagraphWithMenu.svelte, libs/search-widget/src/viewer/paragraphs/Paragraphs.svelte, libs/search-widget/src/viewer/viewer.store.ts
- Display two types of labels: labels from computed metadata and annotated labels from UserFieldMetadata field.
- Don't allow to modify computed labels. Only annotated labels can be modified.
=> [sc-2449] Fix label annotation

libs/search-widget/src/viewer/Metadata.scss, libs/search-widget/src/viewer/Metadata.svelte
This reverts commit 572cf83b0f3eb54b6d0a775dc00da9e2d7200c4f.
=> Revert "Ability to scroll in entity list (#280)"

libs/search-widget/src/old-components/viewer/Metadata.svelte
- Provide a default value for the download URL list
=> [sc-2485] fix error that happens when closing the preview in private knowledge boxes

libs/chrome-ext/src/lib/background.js, libs/chrome-ext/src/lib/manifest.json, libs/chrome-ext/src/lib/utils.js
An error message is displayed when the user tries to upload a Youtube link that is not a video, playlist or channel.
=> [sc-2554] Avoid upload of unsupported YouTube links

apps/dashboard/src/app/upload/upload-files/upload-files.component.ts, apps/desktop/src/environments_config/production/app-config.json, libs/core/src/lib/ui/file-upload/file-drop.directive.ts, libs/core/src/lib/ui/file-upload/file-drop.utils.ts
- Fix desktop app metrics
- Fix folder upload in desktop app
=> [sc-2580] Fix desktop app metrics

apps/dashboard/src/app/resources/resource-list.component.ts, libs/common/src/lib/pagination/pagination.component.html, libs/common/src/lib/pagination/pagination.component.ts
Fix https://github.com/nuclia/support/issues/1
=> Fix resource list page number [sc-2696]

apps/dashboard/src/app/components/topbar/topbar.component.ts, apps/dashboard/src/app/widgets/edit/edit-widget.component.ts, libs/search-widget/src/widgets/search-widget/Widget.svelte
- Convert camel case attribute to lowercase
=> [sc-2736] fix typo

apps/desktop/electron/src/app/app.ts, package.json
- Make sure fullscreen desktop app gets focus when returning from browser
=> [sc-2608] Fix desktop app in full screen

libs/pastanaga/src/lib/icons/icons.ts, libs/search-widget/src/common/icons/MimeIcon.svelte
- Define a default icon for resources with video
=> [sc-2867] Display video icon for resources with video

.github/workflows/deploy.yml
This reverts commit b5560223b83316a37a56711910b8174a9dac890c.
=> Revert "Update git-tag-action to use node 16 (#351)"

libs/search-widget/src/common/label/Label.svelte, libs/search-widget/src/old-components/search-input/SearchInput.scss, libs/search-widget/src/old-components/search-input/SearchInput.svelte
- Set a min-width on suggestion dropdown
- Input inherit background color
- Fix Label on:remove listener
=> Fix [sc-2965]: set a min-width on suggestion dropdown

apps/dashboard/src/app/resources/resource-list.component.ts, libs/sdk-core/protobuf/nucliadb_protos/knowledgebox.proto, libs/sdk-core/protobuf/nucliadb_protos/noderesources.proto, libs/sdk-core/protobuf/nucliadb_protos/resources.proto, libs/sdk-core/protobuf/nucliadb_protos/writer.proto, libs/sdk-core/src/lib/db/db.models.ts, libs/sdk-core/src/lib/db/resource/resource.models.ts
=> Use last_account_seq to compute the processing status count value

apps/dashboard/src/app/setup/setup-step2/setup-step2.component.html, apps/dashboard/src/app/setup/setup-step2/setup-step2.component.ts
- Prevent double click on "Next step" button when creating the first account and knowledge box
- If knowledge box creation fails, don't try to create the account again
=> [sc-3034] clicking on next step twice is generating an error

apps/search-widget-demo/src/App.svelte, libs/sdk-core/src/lib/db/search/search.models.ts, libs/search-widget/src/tiles/pdf-tile/PdfTile.svelte, libs/search-widget/src/tiles/pdf-tile/PdfViewer.svelte, libs/search-widget/src/widgets/search-video-widget/SearchResults.svelte
- Display page indicator on PDF tile when page number is available
- When clicking on a paragraph, if not found by pdfjs, display the corresponding page
=> [sc-3023] Display page indicator when available

apps/search-widget-demo/src/App.svelte, apps/search-widget-demo/vite.config.js, apps/sistema-demo/src/app/sistema-pages/pastanaga-pages-override/sistema-buttons/sistema-buttons.component.html, apps/sistema-demo/src/app/sistema-pages/pastanaga-pages-override/sistema-buttons/sistema-buttons.component.scss, apps/sistema-demo/src/app/sistema-pages/pastanaga-pages-override/sistema-buttons/sistema-buttons.component.ts, libs/search-widget/src/common/button/Button.scss, libs/search-widget/src/common/index.ts, libs/sistema/theme/tokens/_buttons.tokens.scss
- no more shadow on hover
- darker hover and active state for primary and destructive buttons
- update secondary basic buttons to be aligned with the others
=> [sc-3123] Update button theme

libs/search-widget/src/core/search-bar.ts
=> Revert "display ML labels in search results"

libs/common/src/assets/i18n/ca.json, libs/common/src/assets/i18n/en.json, libs/common/src/assets/i18n/es.json
Fix typo: lower case consistency for kb states
=> [sc-3127] Dashboard home page improvements

libs/prediction/src/lib/bert/model.ts, libs/prediction/src/lib/bert/tokenizer.ts, libs/prediction/src/lib/prediction.ts, libs/search-widget/src/widgets/search-video-widget/SearchBar.svelte, libs/search-widget/src/widgets/search-widget/Widget.svelte, libs/search-widget/src/widgets/viewer-widget/ViewerWidget.svelte
Some small changes to adapt the search intent inference to multilingual and to the use of a the DistilbertModel
=> Classifier changes

apps/dashboard/src/app/widgets/widget-generator.component.scss, libs/search-widget/src/common/paragraph-result/ParagraphResult.svelte, libs/search-widget/src/core/api.ts, libs/search-widget/src/core/utils.ts
- Fix time indicator on paragraph results
- Improve widget generator preview layout for tiles
=> [sc-3278] Fix time indicator on tile widget

libs/prediction/src/lib/bert/model.ts
Adding some changes so that we calculate the meanpooling layer for SE models in the front.
=> Add mean pooling method

apps/dashboard/src/app/resources/sample-dataset/dataset-import.component.spec.ts, apps/dashboard/src/app/resources/sample-dataset/dataset-import.component.ts, apps/dashboard/src/app/resources/sample-dataset/sample-dataset.service.ts, apps/dashboard/src/app/services/labels.service.ts, libs/sdk-core/src/lib/db/kb/kb.models.ts, libs/sdk-core/src/lib/db/kb/kb.ts
Check if sample labelSet is there instead.
=> No search endpoint to display sample dataset button

apps/dashboard/src/app/components/hint/hint.component.scss, apps/dashboard/src/app/components/label/label-dropdown/label-dropdown.component.html, apps/dashboard/src/app/components/label/label-dropdown/label-dropdown.component.scss, apps/dashboard/src/app/components/label/label-field/label-field.component.html, apps/dashboard/src/app/components/label/label-field/label-field.component.scss, apps/dashboard/src/app/components/label/label-field/label-field.component.ts, apps/dashboard/src/app/knowledge-box/service-access/service-access.component.scss, apps/dashboard/src/app/upload/upload-text/upload-text.component.html, apps/dashboard/src/app/upload/upload-text/upload-text.component.scss, libs/common/src/assets/i18n/ca.json, libs/common/src/assets/i18n/en.json, libs/common/src/assets/i18n/es.json, libs/pastanaga/src/lib/styles/partials/_typography-utils.scss, libs/sistema/styles/_apps-common.scss, mrs.developer.json
+  Fix position of checkbox option in label dropdown
=> [sc-3252] Re-style upload csv following new design

libs/search-widget/src/common/indicators/PageIndicator.svelte, libs/search-widget/src/tiles/_tile.scss, libs/search-widget/src/tiles/audio-tile/AudioTile.svelte, libs/search-widget/src/tiles/base-tile/DocumentTile.svelte, libs/search-widget/src/tiles/pdf-tile/PdfTile.svelte, libs/search-widget/src/tiles/pdf-tile/PdfViewer.scss, libs/search-widget/src/tiles/pdf-tile/PdfViewer.svelte, libs/search-widget/src/tiles/video-tile/VideoTile.svelte
- Make result title clickable
- Fix audio file loading when current field is generic
- Add spinner to PDF view while loading the PDF
- Display page indicator even when we don't know the page
=> [sc-3422] Make result titles clikable

apps/dashboard/src/app/resources/resource-list.component.ts
- Don't display status column in "Column displayed" options
- Make resource list params persistent
=> [sc-3427] persistent resource list params

apps/dashboard/src/app/widgets/widget-generator.component.html, apps/dashboard/src/app/widgets/widget-generator.component.ts
- [sc-3419]: Select new widget by default in widget editor
- [sc-3426] Make widget editor entries persistent
- Remove timeout before generating snippet
=> Widget editor page improvements

apps/dashboard/src/app/widgets/widget-generator.component.html, libs/search-widget/src/core/api.ts, libs/search-widget/src/core/stores/effects.ts, libs/search-widget/src/core/stores/suggestions.store.ts, libs/search-widget/src/old-components/search-input/SearchInput.svelte, libs/search-widget/src/old-components/suggestions/Suggestions.svelte, libs/search-widget/src/widgets/search-video-widget/SearchBar.svelte
- Enable suggestions in the new widget
- Show only resource titles In the paragraph suggestion list
- Be able to change the search input value without triggering the suggestions
=> [sc-3425] Suggestions in new widget

libs/search-widget/src/common/dropdown/Dropdown.scss, libs/search-widget/src/common/dropdown/Dropdown.svelte, libs/search-widget/src/old-components/search-input/SearchInput.scss, libs/search-widget/src/old-components/search-input/SearchInput.svelte
- Change position of Dropdown components to `fixed`
=> [sc-3678] Label menu scroll bug

libs/sdk-core/src/lib/db/search/search.ts
=> Fix search with POST method

libs/common/src/lib/user/onboarding/onboarding.component.html, libs/common/src/lib/user/onboarding/onboarding.component.scss, libs/common/src/lib/user/user-container/user-container.component.html, libs/common/src/lib/user/user-container/user-container.component.scss, libs/common/src/lib/user/user-container/user-container.component.ts, libs/sistema/theme/tokens/_spacing.tokens.scss
- Add input to align user-container content on top on "small" screens
- Setup vertical scrolling when needed on user-container
- Reduce the spacing on onboarding form
=> Fix spacing on onboarding + user-container layout

apps/dashboard/src/app/resources/edit/annotation/paragraph-annotation/paragraph-annotation.component.ts
When double-clicking on a word on firefox, we can end up with selection like `\t Sinbad`. We trim the selection but need to know how many characters were trimmed, so we can then have the right positions
=> Fix annotation bad position on firefox

apps/dashboard/src/app/resources/resource-list.component.ts
We were listing all labels while we can only add resource labels on resource list.
=> Fix label sets options on resource list

apps/dashboard/src/app/services/entities.service.ts, libs/sdk-core/src/lib/db/kb/kb.models.ts
entity management page needs to load all entities.
=> Fix entities management page

apps/dashboard/src/app/label-sets/label-set/label-set.component.html, apps/dashboard/src/app/label-sets/label-set/label-set.component.scss, apps/dashboard/src/app/label-sets/label-set/label-set.component.ts, apps/dashboard/src/app/label-sets/label-set/label/label.component.html, apps/dashboard/src/app/label-sets/label-set/label/label.component.ts
- label component:
- emit titleChange event on blur
- don't display duplication error when there is no change done
- Prevent save button to move when a new label is added
=> Fix [sc-3984]: label set edition bugs

apps/search-widget-demo/src/App.svelte, libs/sdk-core/CHANGELOG.md, libs/sdk-core/src/lib/db/search/search.models.ts, libs/search-widget/src/core/search-bar.ts, libs/search-widget/src/core/stores/search.store.ts, libs/search-widget/src/tiles/Tile.svelte
- Always load resource values on search triggered from SearchBar
- Add `fieldData` to smart results
- Chose tile depending on its field type:
- video for youtube links,
- depends on content type for files
- text tile as fallback
=> [sc-4001]: Display Tile corresponding to field type

apps/dashboard/src/app/resources/edit/_edit-resource.tokens.scss, apps/dashboard/src/app/resources/edit/annotation/paragraph-annotation/paragraph-annotation.component.scss, apps/dashboard/src/app/resources/edit/annotation/paragraph-annotation/paragraph-annotation.component.ts, apps/dashboard/src/app/resources/edit/common-page-layout.scss, apps/dashboard/src/app/resources/edit/preview/preview.component.html, apps/dashboard/src/app/resources/edit/preview/preview.component.scss
- Fix right panel position on annotation page
- Fix viewer button position on preview page
=> [sc-4217] Entity panel and viewer button position

apps/dashboard/src/app/account/account-kbs/account-kbs.component.html, apps/dashboard/src/app/account/account-kbs/account-kbs.component.scss, apps/dashboard/src/app/account/account-kbs/kb-add/kb-add.component.html, apps/dashboard/src/app/account/account-kbs/kb-add/kb-add.component.scss, apps/dashboard/src/app/account/account-manage/account-manage.component.html, apps/dashboard/src/app/account/account-manage/account-manage.component.scss, apps/dashboard/src/app/account/account-nua/client-dialog/client-dialog.component.html, apps/dashboard/src/app/account/account-nua/client-dialog/client-dialog.component.scss, apps/dashboard/src/app/account/account-users/account-users.component.html, apps/dashboard/src/app/account/account-users/account-users.component.scss, apps/dashboard/src/app/account/account.module.ts, apps/dashboard/src/app/knowledge-box/knowledge-box-users/users-manage/users-manage.component.html, apps/dashboard/src/app/knowledge-box/knowledge-box-users/users-manage/users-manage.component.scss, apps/dashboard/src/app/resources/resources.module.ts, apps/dashboard/src/app/upload/_upload-dialog.scss, apps/dashboard/src/app/upload/create-link/create-link.component.html, apps/dashboard/src/app/upload/upload-files/upload-files.component.html, apps/dashboard/src/app/upload/upload-files/upload-files.component.scss, apps/dashboard/src/app/upload/upload.module.ts
- Remove FlexLayoutModule from account module
- Remove FlexLayoutModule from upload module and kb user management
=> [sc-4335] replace fxLayout by proper css 

libs/search-widget/src/components/previewers/Player.scss, libs/search-widget/src/components/previewers/Player.svelte, libs/search-widget/src/components/previewers/Youtube.scss, libs/search-widget/src/tiles/base-tile/BaseTile.scss, libs/search-widget/src/tiles/base-tile/BaseTile.svelte, libs/search-widget/src/tiles/base-tile/MediaTile.svelte, libs/search-widget/src/tiles/viewers/AudioPlayer.scss
- Avoid the video/audio players being cut off on some screen resolutions
=> [sc-4318] Adjust size of media tile

apps/search-widget-demo/src/App.svelte, libs/sdk-core/src/lib/db/resource/resource.helpers.ts, libs/search-widget/src/core/stores/viewer.store.ts, libs/search-widget/src/tiles/base-tile/BaseTile.svelte
- initialize transcripts only when clicking on full transcript button
- filter out paragraphs which are not transcripts
=> Fix [sc-4601]: Prevent widget viewer from getting stuck

libs/common/src/lib/resources/edit-resource/edit-resource.component.html, libs/common/src/lib/resources/edit-resource/edit-resource.component.scss, libs/common/src/lib/resources/edit-resource/edit-resource.component.ts, libs/common/src/lib/resources/edit-resource/edit-resource.helpers.ts, libs/common/src/lib/resources/edit-resource/edit-resource.module.ts, libs/common/src/lib/resources/edit-resource/preview/preview.component.html, libs/common/src/lib/resources/edit-resource/preview/preview.component.scss, libs/common/src/lib/resources/edit-resource/preview/preview.component.ts, libs/sdk-core/CHANGELOG.md, libs/sdk-core/src/lib/db/resource/resource.models.ts
- Display potential error in field preview and field list
- Import missing paTooltip module
- Disable reprocess button when resource status is pending
=> [sc-4677] disable reprocess button when status is pending

apps/manager/src/app/account/account-detail/account-detail.component.ts
Make sure user's permissions are set up before loading account type
=> Fix [sc-4909]: setup isRoot before account type

libs/search-widget/src/common/label/label.utils.ts, libs/search-widget/src/components/search-input/SearchInput.svelte, libs/search-widget/src/components/suggestions/Suggestions.svelte, libs/search-widget/src/core/api.ts, libs/search-widget/src/core/models.ts, libs/search-widget/src/core/search-bar.ts, libs/search-widget/src/core/stores/effects.ts, libs/search-widget/src/core/stores/search.store.ts, libs/search-widget/src/core/stores/suggestions.store.ts
- Fix typing in Suggestions and search-bar.ts
- Refactor search state filters:
- store details about the filters (only labels with their kind for now) instead of storing only the formatted filter
- add title only as query param
- set titleOnly to true only when there is no query and filtering by Resource kind labels
=> [sc-4912] Fix empty query with label

apps/manager-v2/src/app/manage-accounts/account-details/account-details.component.html, apps/manager-v2/src/app/manage-accounts/account-details/account-details.component.ts, apps/manager-v2/src/app/manage-users/user-details/user-details.component.ts, apps/manager-v2/src/app/manage-users/user-list/user-list.component.ts
and reset account store when going back to account list.
=> Manager v2: Improve error management

apps/manager-v2/src/app/app-layout/app-layout.component.ts, apps/manager-v2/src/app/manage-accounts/account-list/account-list.component.html, apps/manager-v2/src/app/manage-accounts/account-list/account-list.component.ts, apps/manager-v2/src/app/manage-accounts/manage-accounts.module.ts, apps/manager-v2/src/app/manage-users/manage-users.module.ts, apps/manager-v2/src/app/manage-users/user-list/user-list.component.html, apps/manager-v2/src/app/manage-users/user-list/user-list.component.ts
- [sc-5396]: Infinite scroll on account and user lists
- [sc-5347]: Prevent empty avatar
=> [sc-5396]: Infinite scroll on account and user lists

.github/workflows/deploy.yml, apps/manager-v2/src/app/manage-accounts/account-details/account-details.component.html
and fix manager deployment (deployment was still relying on the old manager version)
=> [sc-5464] display account id

libs/common/src/lib/knowledge-box-settings/knowledge-box-settings.component.html, libs/common/src/lib/knowledge-box-settings/knowledge-box-settings.component.scss, libs/common/src/lib/knowledge-box-settings/knowledge-box-settings.component.ts
The check we did to know if the configuration changed was always returning false.
=> Fix [sc-5526]: trigger kb configuration update when conf changed

app.babel, apps/dashboard/src/app/knowledge-box/knowledge-box-home/knowledge-box-home.component.ts, libs/common/src/assets/i18n/ca.json, libs/common/src/assets/i18n/en.json, libs/common/src/assets/i18n/es.json, libs/core/src/lib/api/sdk.service.ts
Previous fix was inducing an infinite loop of request publishing and un-publishing the KB. This PR revert the bad fix and fix the bug properly.
Also adding a missing translation
=> Fix [sc-5520] without infinite calls

libs/common/src/lib/select-account-kb/select-kb/select-kb.component.html, libs/common/src/lib/select-account-kb/select-kb/select-kb.component.scss, libs/common/src/lib/select-account-kb/select-kb/select-kb.component.ts, libs/sdk-core/src/lib/auth/auth.ts, libs/sdk-core/src/lib/db/db.ts
- use READER role for /chat endpoint
- add create kb button on select kb page of contributor
=> [sc-5535] wrong role on chat endpoint on contributor

README.md, apps/desktop/src/assets/i18n/es.json, desktop.babel
- Fix typo in spanish translation in the login page
=> Desktop improvements from All hands

apps/search-widget-demo/src/App.svelte, libs/search-widget/src/components/answer/InitialAnswer.scss, libs/search-widget/src/components/answer/InitialAnswer.svelte, tsconfig.base.json
- Smaller and lighter box-shadow
- No more "Answer" title
=> [sc-5620] Generative answer box improvements

libs/common/src/lib/resources/resource-list/resource-list.component.html, libs/common/src/lib/resources/resource-list/resource-list.component.ts, libs/common/src/lib/services/app.service.ts, libs/common/src/lib/upload/upload-text/upload-text.component.ts, libs/common/src/lib/upload/upload.service.ts
- Display empty kb warning only when the kb never had data
- Display dataset selector on resource list only when KB never had data.
=> [sc-5455] better empty kb management

apps/dashboard/src/app/knowledge-box/knowledge-box.module.ts, apps/dashboard/src/app/knowledge-box/service-access/service-access.component.html, apps/dashboard/src/app/knowledge-box/service-access/service-access.component.ts
Display the token dialog immediately after adding the key.
=> Improve API key generation

apps/search-widget-demo/src/App.svelte, libs/search-widget/src/common/_global.scss, libs/search-widget/src/common/button/Button.scss, libs/search-widget/src/common/button/Button.svelte, libs/search-widget/src/common/button/IconButton.svelte, libs/search-widget/src/common/chip/Chip.svelte, libs/search-widget/src/common/common-style.scss, libs/search-widget/src/common/dropdown/Dropdown.scss, libs/search-widget/src/common/modal/Modal.scss, libs/search-widget/src/common/paragraph-result/ParagraphResult.scss, libs/search-widget/src/common/thumbnail/Thumbnail.scss, libs/search-widget/src/components/answer/Chat.scss, libs/search-widget/src/components/answer/ChatInput.scss, libs/search-widget/src/components/suggestions/Suggestions.scss, libs/search-widget/src/tiles/base-tile/BaseTile.scss
- Fix suggestion dropdown position and style
- Tokenize dropdown and thumbnail
- Fix border color of search bar input 
- Simplify token names (remove the `--default` prefix which doesn't makes sense as the custom theme variables are used to initialize the tokens)
=> [sc-6085] fix dark theme

apps/search-widget-demo/.eslintrc.js, libs/search-widget/src/tiles/base-tile/BaseTile.svelte
- Reset sidePanel section shown when closing viewer
- Fix eslint configuration on search-widget-demo app
=> [sc-6139] fix search results after closing viewer

apps/search-widget-demo/src/App.svelte, libs/search-widget/public/i18n/ca.json, libs/search-widget/public/i18n/en.json, libs/search-widget/public/i18n/es.json, libs/search-widget/public/i18n/fr.json, libs/search-widget/src/common/_global.scss, libs/search-widget/src/common/common-style.scss, libs/search-widget/src/common/indicators/DocTypeIndicator.svelte, libs/search-widget/src/components/viewer/Viewer.scss, libs/search-widget/src/components/viewer/Viewer.svelte, libs/search-widget/src/components/viewer/renderers/ConversationRenderer.scss, libs/search-widget/src/components/viewer/renderers/ConversationRenderer.svelte, libs/search-widget/src/components/viewer/renderers/TextRenderer.svelte, libs/search-widget/src/components/viewer/renderers/renderings/ExtractedTextRendering.svelte, libs/search-widget/src/core/api.ts, libs/search-widget/src/core/models.ts, libs/search-widget/src/core/stores/viewer.store.ts, libs/search-widget/src/core/utils.ts, libs/search-widget/widget.babel
- [sc-6051] Access to other fields from viewer
- Fix highlight on ExtractedTextRendering + cleanup deprecated models
- Prevent state update in getExtractedTexts
-  Fix dark mode for Text and Conversation renderers
=> [sc-6051] access other fields from viewer

libs/common/src/lib/resources/resource-list/error-resources-table/error-resources-table.component.html, libs/common/src/lib/resources/resource-list/pending-resources-table/pending-resources-table.component.html, libs/common/src/lib/resources/resource-list/resource-list.component.html
- Enable bulk reprocessing on pending view
- Enable sorting on both pending and error views
=> [sc-6792]: Fix pending and error views

libs/common/src/lib/select-account-kb/select-account/select-account.component.ts
even if there's several kbs in the account
=> Fix [sc-6803]: don't display account selection screen when there's only one account

libs/common/src/lib/knowledge-box-settings/knowledge-box-settings.component.html, libs/common/src/lib/resources/resource-list/resource-list.component.ts, libs/common/src/lib/resources/sample-dataset/dataset-selector/dataset-selector.component.spec.ts, libs/common/src/lib/resources/sample-dataset/dataset-selector/dataset-selector.component.ts, libs/common/src/lib/select-account-kb/select-kb/select-kb.component.html
- Fix create kb button label on select-kb page
- Fix kb settings label translation
- Fix translation keys for dataset import
=> Fix broken translations

apps/dashboard/src/app/account/account-manage/account-manage.component.html, apps/dashboard/src/app/account/account-manage/account-manage.component.scss, libs/common/src/assets/i18n/ca.json, libs/common/src/assets/i18n/en.json, libs/common/src/assets/i18n/es.json, libs/common/src/assets/i18n/fr.json, libs/common/src/lib/knowledge-box-settings/knowledge-box-settings.component.html, libs/common/src/lib/knowledge-box-settings/knowledge-box-settings.component.scss, libs/common/src/lib/resources/edit-resource/_edit-resource.tokens.scss, libs/common/src/lib/resources/edit-resource/add-field/add-field.component.html, libs/common/src/lib/resources/edit-resource/common-page-layout.scss, libs/common/src/lib/resources/edit-resource/edit-resource.module.ts, libs/common/src/lib/resources/edit-resource/profile/link/link.component.html, libs/common/src/lib/resources/edit-resource/profile/profile.component.html, libs/common/src/lib/resources/edit-resource/profile/profile.component.scss, libs/user/src/lib/profile/profile.component.html, libs/user/src/lib/profile/profile.component.scss
Without external label, we also gain space on the forms.
Done in:
- knowledge-box-settings
- resource edition flow
- user preferences
- account details
=> [sc-6862]: Improve consistency by using default sistema fields

libs/common/common.babel, libs/common/src/assets/i18n/ca.json, libs/common/src/assets/i18n/en.json, libs/common/src/assets/i18n/es.json, libs/common/src/assets/i18n/fr.json, libs/common/src/lib/upload/create-link/create-link.component.ts, libs/common/src/lib/upload/upload-text/upload-text.component.ts, libs/common/src/lib/upload/upload.service.ts
- Links and text resources are created in batches to avoid performance issues
- A failure creating a link or text resource doesn't impact the other resources
=> [sc-6341] Improve creation of multiple resources

apps/dashboard/src/app/account/account-nua/nua-activity/nua-activity.service.ts, apps/dashboard/src/app/app.component.ts, apps/dashboard/src/app/knowledge-box/knowledge-box-users/knowledge-box-users.component.ts, apps/dashboard/src/app/knowledge-box/knowledge-box.module.ts, apps/dashboard/src/app/knowledge-box/service-access/service-access.component.ts, apps/desktop/src/app/app.component.ts, libs/common/src/lib/knowledge-box-settings/knowledge-box-settings.component.scss, libs/common/src/lib/knowledge-box-settings/knowledge-box-settings.component.ts, libs/common/src/lib/resources/resource-list/resource-list.component.ts, libs/common/src/lib/services/navigation.service.ts, libs/core/src/lib/api/sdk.service.ts, libs/core/src/lib/state.service.ts, libs/user/src/lib/magic/magic.service.ts
- Update KB list whenever account changes
- Remove useless methods dbGetStateData, dbSetStateData and dbDelStateData
- Fix KB settings form and slug update
=> [sc-6247] kb list is not updated when it should

libs/sdk-core/CHANGELOG.md, libs/sdk-core/src/lib/db/search/chat.ts, libs/sdk-core/src/lib/db/search/search.models.ts, libs/sdk-core/src/lib/rest/rest.ts, libs/search-widget/src/core/api.ts
Allowing to get the response as a JSON instead of a stream
=> [sc-7165] Add synchronous option to `/chat` endpoint

apps/desktop/src/app/history/history.component.html, apps/sistema-demo/src/app/sistema-pages/pastanaga-pages-override/sistema-toasts/sistema-toast.component.html, libs/common/src/lib/resources/resource-list/error-resources-table/error-resources-table.component.html, libs/common/src/lib/resources/resource-list/pending-resources-table/pending-resources-table.component.html, libs/common/src/lib/resources/resource-list/processed-resource-table/processed-resource-table.component.html, libs/common/src/lib/resources/resource-list/resource-list.component.html, libs/common/src/lib/resources/resource-list/resource-list.component.scss, libs/common/src/lib/resources/resource-list/resources-table.component.scss, libs/common/src/lib/topbar/topbar.component.html, libs/common/src/lib/upload/upload-progress/upload-progress.component.html, libs/sistema/src/lib/sis-toast.service.spec.ts, libs/sistema/src/lib/sis-toast.service.ts, libs/sistema/src/lib/status/status.component.ts
- replace circle-cross icons by warning ones
- update status buttons to be icon+text and standardize colors
=> [sc-7067] improve error status look throughout apps

libs/common/src/lib/entities/entities.component.html, libs/common/src/lib/entities/entities.component.scss, libs/common/src/lib/entities/entities.component.ts
Modification of the buttons to edit/delete a NER family:
- improve button styles
- show buttons when hovering over a family
=> [sc-7267] Improve buttons in entities management

libs/common/src/lib/resources/edit-resource/edit-resource.module.ts, libs/common/src/lib/resources/resource-list/error-resources-table/error-resources-table.component.html, libs/common/src/lib/resources/resource-list/error-resources-table/error-resources-table.component.spec.ts, libs/common/src/lib/resources/resource-list/error-resources-table/error-resources-table.component.ts, libs/common/src/lib/resources/resource-list/index.ts, libs/common/src/lib/resources/resource-list/pending-resources-table/pending-resources-table.component.html, libs/common/src/lib/resources/resource-list/pending-resources-table/pending-resources-table.component.spec.ts, libs/common/src/lib/resources/resource-list/pending-resources-table/pending-resources-table.component.ts, libs/common/src/lib/resources/resource-list/processed-resource-table/processed-resource-table.component.html, libs/common/src/lib/resources/resource-list/processed-resource-table/processed-resource-table.component.spec.ts, libs/common/src/lib/resources/resource-list/processed-resource-table/processed-resource-table.component.ts, libs/common/src/lib/resources/resource-list/resource-list.component.html, libs/common/src/lib/resources/resource-list/resource-list.component.scss, libs/common/src/lib/resources/resource-list/resource-list.component.ts, libs/common/src/lib/resources/resource-list/resource-list.model.ts, libs/common/src/lib/resources/resource-list/resource-list.service.ts, libs/common/src/lib/resources/resource-list/resources-table.component.scss, libs/common/src/lib/resources/resource-list/resources-table.directive.ts, libs/common/src/lib/resources/resources.module.ts, libs/common/src/lib/upload/upload-data/upload-data.component.ts, libs/common/src/lib/upload/upload.module.ts, libs/common/src/lib/upload/upload.service.ts
- Resource list refactoring using routing
- Redirect to pending resources after uploading from upload data page
=> [sc-7012] Resource list refactoring using routing

libs/common/src/lib/resources/edit-resource/edit-resource.component.html, libs/common/src/lib/resources/edit-resource/edit-resource.component.ts, libs/common/src/lib/resources/edit-resource/select-first-field/select-first-field.directive.ts, libs/common/src/lib/resources/resource-list/processed-resource-table/processed-resource-table.component.ts
- Preserve filtering in resource list
- Fix browser back button from edit resource view
=> [sc-7078] Preserve filtering in resources list

yarn.lock
Following instructions:
> Browserslist: caniuse-lite is outdated. Please run:
>  npx update-browserslist-db@latest
>  Why you should do it regularly: https://github.com/browserslist/update-db#readme
=> npx update-browserslist-db@latest

apps/manager-v2/src/app/manage-accounts/account-details/account-details.component.html, apps/manager-v2/src/app/manage-accounts/account-details/configuration/configuration.component.ts, apps/manager-v2/src/app/manage-accounts/account-details/kb-details/kb-details.component.ts, apps/manager-v2/src/app/manage-accounts/account-details/knowledge-boxes/knowledge-boxes.component.html, apps/manager-v2/src/app/manage-accounts/account-ui.models.ts, apps/manager-v2/src/app/manage-accounts/account.service.ts, apps/manager-v2/src/app/manage-accounts/global-account.models.ts, apps/manager-v2/src/app/manage-accounts/global-account.service.ts, apps/manager-v2/src/app/manage-accounts/manage-accounts.module.ts, apps/manager-v2/src/app/manage-accounts/regional-account.models.ts, apps/manager-v2/src/app/manage-accounts/regional-account.service.ts, apps/manager-v2/src/app/manage-users/user.service.ts, apps/manager-v2/src/app/manage-zones/zone.service.ts, libs/sdk-core/CHANGELOG.md, libs/sdk-core/src/lib/db/db.models.ts, libs/sdk-core/src/lib/models.ts, libs/sdk-core/src/lib/rest/rest.ts
Usage of regional endpoints is enabled be setting `NUCLIA_NEW_REGIONAL_ENDPOINTS` to true on the local storage.
=> [sc-7476] manager implement new regional endpoints

libs/sdk-core/src/lib/rest/rest.ts
Fixing regression included when removing DeprecatedAPI service
=> Fix account creation and password recover

apps/search-widget-demo/src/App.svelte, libs/search-widget/src/components/search-filters/SearchFilters.scss, libs/search-widget/src/components/search-filters/SearchFilters.svelte, libs/search-widget/src/components/search-input/SearchInput.scss, libs/search-widget/src/components/search-input/SearchInput.svelte
- Improve search filters dropdown
- Display all filters applied
=> [sc-7650] Improve search widget filters

apps/dashboard/src/app/knowledge-box/knowledge-box-users/users-manage/users-manage.component.html, apps/dashboard/src/app/knowledge-box/service-access/service-access.component.html, libs/common/common.babel, libs/common/src/assets/i18n/ca.json, libs/common/src/assets/i18n/de.json, libs/common/src/assets/i18n/en.json, libs/common/src/assets/i18n/es.json, libs/common/src/assets/i18n/fr.json, libs/common/src/assets/i18n/pt.json, libs/common/src/lib/entities/entities.component.html, libs/common/src/lib/entities/entities.component.scss, libs/common/src/lib/entities/entities.component.ts, libs/common/src/lib/entities/entity-list/entity-list.component.ts, libs/sistema/theme/tokens/_textfield.tokens.scss, mrs.developer.json
and  update text fields to be 40px high (instead of 48px)
=> [sc-7713] Implement the new entities mgt page

libs/search-widget/src/components/search-filters/SearchFilters.svelte, libs/search-widget/src/components/search-input/SearchInput.svelte
- When search filters change, they are applied immediately.
- In the case of the filters dropdown, filters are applied as soon as the dropdown is closed.
=> [sc-7880] Apply filters on selection

apps/search-widget-demo/src/App.svelte, libs/common/src/lib/widgets/widget-generator.component.ts, libs/search-widget/src/widgets/search-widget/SearchBar.svelte
And fix widget generator to use search event dispatched by the widget to send the request whenever permalink is false.
=> [sc-7916] Fix dispatch custom event in widget

libs/common/common.babel, libs/common/src/assets/i18n/ca.json, libs/common/src/assets/i18n/en.json, libs/common/src/assets/i18n/es.json, libs/common/src/assets/i18n/fr.json, libs/common/src/lib/entities/entity-list/entity-list.component.html, libs/common/src/lib/entities/entity-list/entity-list.component.scss, libs/common/src/lib/entities/entity-list/entity-list.component.ts
Display no more than 1000 rows in the NER list, and display a message when some NERs are hidden.
=> [sc-7250] Prevent NER management page to get frozen

libs/common/common.babel, libs/common/src/assets/i18n/ca.json, libs/common/src/assets/i18n/en.json, libs/common/src/assets/i18n/es.json, libs/common/src/assets/i18n/fr.json, libs/common/src/lib/navbar/navbar.component.html, libs/common/src/lib/widgets/widget-generator.component.scss, mrs.developer.json
- Fix private KB warning in widget generator page [sc-7912]
- Fix [sc-8024]: French translation of upload data item
- Fix [sc-7953]: Long option name in select
=> Fix private KB warning in widget generator page [sc-7912]

apps/dashboard/src/app/app.module.ts, libs/common/src/lib/guards/auth.interceptor.ts, libs/sync/src/lib/sync/new-models.ts, libs/sync/src/lib/sync/new-sync.service.ts, libs/sync/src/lib/upload/settings/settings.component.ts
=> use sync agent

apps/search-widget-demo/src/App.svelte, libs/common/common.babel, libs/common/src/assets/i18n/ca.json, libs/common/src/assets/i18n/en.json, libs/common/src/assets/i18n/es.json, libs/common/src/assets/i18n/fr.json, libs/common/src/lib/resources/edit-resource/edit-resource.component.html, libs/common/src/lib/resources/edit-resource/preview/preview.component.html, libs/common/src/lib/resources/edit-resource/select-first-field/select-first-field.directive.ts, libs/common/src/lib/resources/resource-list/resource-list.component.scss, libs/search-widget/src/core/stores/search.store.ts
- In the widget and the resource edit flow, don't crash when a resource doesn't have any field
- Fix layout bug: Resource list was visible behind the header when scrolling down
=> [sc-8118]: Support resources without fields

apps/dashboard/src/app/account/account-nua/client-dialog/client-dialog.component.html, apps/dashboard/src/app/account/account-nua/client-dialog/client-dialog.component.scss, apps/dashboard/src/app/account/account-nua/client-dialog/client-dialog.component.ts
New feature flag: `allow-kb-management-from-nua-key`
=> [sc-8087] Hide "allow management of KBs" in NUA

apps/dashboard/src/app/app.module.ts, apps/dashboard/src/app/knowledge-box/knowledge-box-home/knowledge-box-home.component.scss, mrs.developer.json
- home page layout on small screens
- avoiding cache issue with glyphs sprite
=> Fix [sc-8150] and [sc-8152]

apps/dashboard/src/app/account/account-manage/account-delete/account-delete.component.ts, libs/common/src/lib/topbar/user-menu/user-menu.component.html, libs/user/src/lib/onboarding/onboarding.service.ts
- User information is refreshed whenever an account is created or deleted
=> [sc-8283] fix user menu after account creation

libs/common/src/lib/knowledge-box-settings/knowledge-box-settings.component.html, libs/common/src/lib/knowledge-box-settings/knowledge-box-settings.component.ts, libs/common/src/lib/select-account-kb/select-kb/select-kb.component.html
(translation + empty fields management)
=> Fix KB settings in NucliaDB admin

apps/dashboard/src/app/knowledge-box/knowledge-box-users/users-manage/users-manage.component.ts, apps/dashboard/src/app/knowledge-box/knowledge-box-users/users-manage/users-manage.service.ts
=> [sc-8686] Allow existing users in an account to be directly added to a KB

libs/common/src/lib/resources/resource-list/resource-list.service.ts
Now the new endpoint for `processing-status` is enabled/disabled for all KBs, we don't need to call the old `/processing/status` anymore when the feature flag is enabled.
=> [sc-8737] don't call /processing/status  when feature flag for new endpoint is enabled

libs/core/src/lib/analytics/feature-flag.service.ts, libs/core/src/lib/analytics/features.service.ts
- Add support for backend feature flag
- Use NucliaDB flag for new processing status endpoint
=> [sc-8738] Support backend feature flags

apps/dashboard/src/app/knowledge-box/knowledge-box-home/knowledge-box-home.component.html, apps/dashboard/src/app/knowledge-box/knowledge-box-home/knowledge-box-home.component.ts
Track more metrics from the home page usage
=> Fix [sc-8910]: don't show usage charts when only a member of the KB

.github/workflows/deploy.yml
This reverts commit 9f7724d31471e71c1ecf784f921331366010ada2.
=> Revert "push images to the new Artifact Repository (#1325)"

.github/workflows/deploy.yml
This reverts commit c0dfafdf4fb716e5e7a6ec657fed0f84846fbd15.
=> Revert "run on self-hosted-runners (#1329)"

libs/common/src/assets/i18n/es.json, libs/common/src/lib/prompt-lab/prompt-lab.component.scss, libs/common/src/lib/prompt-lab/prompt-lab.component.ts
- [sc-8950] Fix spacing in prompt lab results
- [sc-8935] Reset progress when generating new answers
- Fix bad spanish translation in upload modal
=> [sc 8935] processing line appears outside the modal in prompt lab

apps/manager-v2/src/app/app-layout/app-layout.component.scss, apps/manager-v2/src/app/app.component.scss, apps/manager-v2/src/app/manage-accounts/account-details/account-details.component.html, apps/manager-v2/src/app/manage-accounts/account-details/account-details.component.scss, apps/manager-v2/src/app/manage-accounts/account-details/account-details.component.spec.ts, apps/manager-v2/src/app/manage-accounts/account-details/blocked-features/blocked-features.component.scss, apps/manager-v2/src/app/manage-accounts/account-details/configuration/configuration.component.scss, apps/manager-v2/src/app/manage-accounts/account-details/kb-details/kb-details.component.html, apps/manager-v2/src/app/manage-accounts/account-details/kb-details/kb-details.component.scss, apps/manager-v2/src/app/manage-accounts/account-details/kb-details/kb-details.component.ts, apps/manager-v2/src/app/manage-accounts/account-details/knowledge-boxes/knowledge-boxes.component.html, apps/manager-v2/src/app/manage-accounts/account-details/limits/limits.component.scss, apps/manager-v2/src/app/manage-accounts/account-details/users/users.component.scss, apps/manager-v2/src/app/manage-accounts/account-ui.models.ts, apps/manager-v2/src/app/manage-accounts/regional-account.service.ts, apps/manager-v2/src/app/manage-zones/zone-list/zone-list.component.html, apps/manager-v2/src/app/manage-zones/zone-list/zone-list.component.spec.ts, apps/manager-v2/src/app/manage-zones/zone-list/zone-list.component.ts, apps/manager-v2/src/app/manage-zones/zone.service.ts
- Fix variable import in scss
- Display zones in account details sidenav
- Fix loadKbCounters method and add zone in KB table
- Add zone in KB details
=> [sc-8897] manager display the zone of each kb

.github/workflows/deploy.yml
Also,
- make env var CONTAINER_REGISTRY local to every step
- switch to workload identity
=> frontend pushes images to Artifact Registry too

apps/dashboard/src/app/account/account-nua/client-dialog/client-dialog.component.ts
- when there is only one zone, select it
- otherwise, select the account zone if any
=> Fix [sc-9090]: NUA key creation dialog

libs/common/src/lib/widgets/widget-generator.component.html, libs/common/src/lib/widgets/widget-generator.component.ts
Hide generative model toggle and selection when schema fails
=> [sc-9203] Trigger content loaded when presets are loaded

apps/dashboard/src/app/account/account-nua/client-dialog/client-dialog.component.html, libs/core/src/lib/api/zone.service.ts
Make sure to take only 1 account, so we don't block forkJoins when using `getZones`
=> Fix getZones again

apps/manager-v2/src/app/manage-zones/zone-details/zone-details.component.html, apps/manager-v2/src/app/manage-zones/zone-details/zone-details.component.ts, apps/manager-v2/src/app/manage-zones/zone-list/zone-list.component.html, apps/manager-v2/src/app/manage-zones/zone.models.ts
- Add `subdomain` and `cloud_provider` in Manager’s zone model
- Add subdomain and cloud provider in zone form and zone list
- Update zone list after adding a zone
=> [sc-9112] Update zone form in manager

apps/dashboard/src/app/onboarding/getting-started/getting-started.component.ts, apps/dashboard/src/app/onboarding/getting-started/getting-started.models.ts, apps/dashboard/src/app/onboarding/getting-started/upload-list/upload-list.component.html, apps/dashboard/src/app/onboarding/getting-started/upload-list/upload-list.component.ts, libs/common/common.babel, libs/common/src/assets/i18n/ca.json, libs/common/src/assets/i18n/en.json, libs/common/src/assets/i18n/es.json, libs/common/src/assets/i18n/fr.json, libs/common/src/lib/resources/resource-list/resource-list.service.ts, libs/common/src/lib/upload/upload.service.ts, libs/sdk-core/CHANGELOG.md, libs/sdk-core/src/lib/db/db.models.ts, libs/sdk-core/src/lib/db/db.ts, libs/sdk-core/src/lib/models.ts
- Remove deprecated method `getProcessingStatus` from `db`
- Use kb `processingStatus` method instead in getting started component
=> [sc-9290] Fix getting started flow

apps/sistema-demo/src/app/app.component.ts, apps/sistema-demo/src/app/sistema-pages/sistema-cards/sistema-info-card.component.html, apps/sistema-demo/src/app/sistema-pages/sistema-cards/sistema-info-card.component.ts, apps/sistema-demo/src/app/sistema-pages/sistema-two-columns-configuration-item/sistema-two-columns-configuration-item.component.html, apps/sistema-demo/src/app/sistema-pages/sistema-two-columns-configuration-item/sistema-two-columns-configuration-item.component.ts, apps/sistema-demo/src/index.html, libs/sistema/src/index.ts, libs/sistema/src/lib/cards/info-card/info-card.component.scss, libs/sistema/src/lib/cards/info-card/info-card.component.ts, libs/sistema/src/lib/two-columns-configuration-item/index.ts, libs/sistema/src/lib/two-columns-configuration-item/two-columns-configuration-item.component.html, libs/sistema/src/lib/two-columns-configuration-item/two-columns-configuration-item.component.scss, libs/sistema/src/lib/two-columns-configuration-item/two-columns-configuration-item.component.ts
- [sc-9264] new two-columns-configuration-item component
- update info-card: add support for highlight and warning use cases
=> [sc-9264] new two-columns-configuration-item component

apps/dashboard/src/app/knowledge-box/knowledge-box-training/training-history/training-history.component.html, apps/search-widget-demo/src/App.svelte, apps/sistema-demo/src/app/sistema-pages/sistema-back-button/sistema-back-button.component.html, apps/sistema-demo/src/app/sistema-pages/sistema-back-button/sistema-back-button.component.ts, apps/sistema-demo/src/app/sistema-pages/sistema-label/sistema-label.component.html, apps/sistema-demo/src/app/sistema-pages/sistema-label/sistema-label.component.ts, apps/sistema-demo/src/app/sistema-pages/sistema-pages.module.ts, libs/common/src/lib/widgets/widget-generator.component.scss, libs/search-widget/src/common/common-style.scss, libs/search-widget/src/components/search-input/SearchInput.scss, libs/search-widget/src/components/viewer/Viewer.scss, libs/sistema/src/lib/back-button/back-button.component.html, libs/sistema/src/lib/back-button/back-button.component.scss, libs/sistema/src/lib/back-button/back-button.component.ts, libs/sistema/src/lib/label/label.component.scss, libs/sistema/src/lib/labels-expander/labels-expander.component.html, libs/sistema/src/lib/labels-expander/labels-expander.component.scss, libs/sistema/src/lib/password-input/password-input.component.html, libs/sistema/src/lib/password-input/password-input.component.scss, libs/sistema/theme/tokens/_buttons.tokens.scss, libs/sistema/theme/tokens/_chips.tokens.scss, libs/sistema/theme/tokens/_spacing.tokens.scss, libs/sistema/theme/tokens/_toggle.tokens.scss, mrs.developer.json
- Update toggles size and color
- Update border-radius to be 4px everywhere
- Add solid border on basic buttons (except on icon buttons)
- Fix labels demo page + improve padding
- Update back-button to be just a link
- Update border color of Search widget
=> [sc-9350] Quick wins on the UI

apps/dashboard/src/app/account/account-kbs/account-kbs.component.html, apps/dashboard/src/app/account/account-kbs/account-kbs.component.scss, libs/common/common.babel, libs/common/src/assets/i18n/ca.json, libs/common/src/assets/i18n/en.json, libs/common/src/assets/i18n/es.json, libs/common/src/assets/i18n/fr.json, libs/common/src/lib/kb-add/kb-add-modal.component.ts, libs/common/src/lib/kb-add/kb-creation-form/kb-creation-form.component.html, libs/common/src/lib/kb-add/kb-creation-form/kb-creation-form.component.scss, libs/common/src/lib/kb-add/kb-creation-form/kb-creation-form.component.ts, libs/sdk-core/CHANGELOG.md, libs/sdk-core/src/lib/core.ts, libs/sdk-core/src/lib/db/db.ts, libs/sdk-core/src/lib/db/kb/kb.models.ts, package.json, yarn.lock
- Display a warning in case a KB with same name already exists in the account
- Automatically add a suffix on the KB slug in case of conflict
=> [sc-9376] UX improvements on KB creation

apps/manager-v2/src/app/manage-accounts/account-details/token-consumption/token-consumption.component.html, apps/manager-v2/src/app/manage-accounts/account.service.ts
- Improve display of KB tabs in token consumption page
- Support empty `/usage` response in `loadTokenConsumption` method
=> [sc-9591] Prevent method failure when no usage available

libs/common/src/lib/search-widget/search-configuration/results-display-form/results-display-form.component.ts
Adds gemini 1.5 to generative models with json output enabled
=> add gemini 1.5 to json output list

libs/common/src/lib/search-widget/search-configuration/results-display-form/results-display-form.component.ts
adds azure mistral to models with json output support
=> add azure mistral to models with json output support

libs/common/src/lib/search-widget/search-configuration/results-display-form/results-display-form.component.ts
adds chtagpt4o mini to models with json support
=> adds chtagpt4o mini to models with json support

libs/common/common.babel, libs/common/src/assets/i18n/ca.json, libs/common/src/assets/i18n/en.json, libs/common/src/assets/i18n/es.json, libs/common/src/assets/i18n/fr.json, libs/common/src/lib/search-widget/search-page.component.html, libs/common/src/lib/search-widget/search-page.component.scss, libs/common/src/lib/search-widget/search-page.component.ts
Add a close button on the search configuration panel when the screen is smaller than 1440px.
=> [sc-10782] Toggle config column in search page

libs/core/src/lib/analytics/feature-flag.service.ts
To fix https://app.shortcut.com/flaps/story/10124/feature-flags-not-working-in-onboarding-page, we added a `startWith('')` on `accountMd5` of `FeatureFlagService` to make it work also on onboarding page.
The problem with this first fix, is that `startWith` was in a `combineLatest`, so `accountMd5` was always sending `''` first whenever `applicationRemoteFeatures` was called. This first call with `accountMd5 = ''` introduced the bug https://app.shortcut.com/flaps/story/10815/creating-a-pinecone-kb-from-the-ui-doesn-t-work-in-prod where the pinecone form was displayed but then the form value wasn't sent to the KB creation payload. This is because when submitting the form, we are checking the feature flag with a `take(1)` and the first call was always returning `false` because of this …
=> [sc-10815]: Fix feature flag service

apps/dashboard/src/app/account/account-users/account-users.component.html, apps/dashboard/src/app/account/account-users/account-users.component.ts, apps/dashboard/src/app/knowledge-box/knowledge-box-users/users-manage/users-manage.component.html, apps/dashboard/src/app/knowledge-box/knowledge-box-users/users-manage/users-manage.component.ts, libs/sdk-core/CHANGELOG.md, libs/sdk-core/src/lib/db/kb/kb.ts
- Inviting KB and account users with any role
- KB invitation deletion: encode email before sending it as URL parameter
=> [sc-10872] sharing kb and account with any role

libs/common/src/lib/kb-creation/kb-creation.component.html, libs/common/src/lib/kb-creation/kb-creation.component.ts
=> Revert "more robust kb creation (to fix e2e)"

libs/core/src/lib/api/billing.service.ts, libs/core/src/lib/api/zone.service.ts
-  Simplify getZones: Remove the check for beta testers
- Add optional cache on get subscription
=> [sc-10891] improve method to get zones

apps/manager-v2/project.json, apps/manager-v2/src/app/app.module.ts, apps/manager-v2/src/app/manage-zones/manage-zones.module.ts, apps/manager-v2/src/app/manage-zones/zone-details/zone-details.component.ts, apps/manager-v2/src/app/manage-zones/zone.service.ts, libs/common/src/lib/ai-models/answer-generation/answer-generation.component.html, libs/common/src/lib/ai-models/summarization/summarization.component.html, libs/common/src/lib/charts/line-chart/line-chart.component.html, libs/common/src/lib/knowledge-box-settings/knowledge-box-settings.component.html, libs/common/src/lib/resources/edit-resource/preview/preview.component.html, libs/common/src/lib/search-widget/widgets/dialogs/duplicate-widget-dialog/duplicate-widget-dialog.component.html, libs/common/src/lib/search-widget/widgets/dialogs/embed-widget-dialog/embed-widget-dialog.component.html, libs/common/src/lib/search-widget/widgets/dialogs/rename-widget-dialog/rename-widget-dialog.component.html, libs/common/src/lib/token-dialog/token-dialog.component.html, libs/common/src/lib/validators/form.validator.ts
- Display the token generated after zone creation in a modal
- Adapt token-dialog to display custom title/description
- Add proper validation on zone slug form
- Add common translations to manager app
=> [sc-10934] manager app display token when creating zone

libs/common/src/lib/navbar/navbar.component.html, libs/common/src/lib/navbar/navbar.component.ts
=> Revert "[sc-11003] User menu must be accessible for KB owners"

.github/workflows/deploy.yml
This pull request includes several changes to the `.github/workflows/deploy.yml` file to enhance the deployment workflow. The most important changes include adding a new environment variable, updating action versions, removing redundant steps, and adding a new job to handle promotion summaries.
* Added a new environment variable `PROMO_PRODUCTION` to the `env` section. (`.github/workflows/deploy.yml`)
* Updated the `actions/checkout` action from version 3 to version 4. (`.github/workflows/deploy.yml`) [[1]](diffhunk://#diff-28802fbf11c83a2eee09623fb192785e7ca92a3f40602a517c011b947a1822d3R176-R190) [[2]](diffhunk://#diff-28802fbf11c83a2eee09623fb192785e7ca92a3f40602a517c011b947a1822d3L219-R237)
* Added outputs for JSON summaries in both `deploy-app` and `deploy-manager` jobs. …
=> New pipeline for release

.github/workflows/deploy.yml
This pull request includes updates to the GitHub Actions workflow configuration in the `.github/workflows/deploy.yml` file. The changes enhance the permissions and introduce new environment variables for the deployment process.
Enhancements to GitHub Actions workflow:
* [`.github/workflows/deploy.yml`](diffhunk://#diff-28802fbf11c83a2eee09623fb192785e7ca92a3f40602a517c011b947a1822d3R22): Added `actions: read` permission under the `permissions` section to allow reading actions.
* [`.github/workflows/deploy.yml`](diffhunk://#diff-28802fbf11c83a2eee09623fb192785e7ca92a3f40602a517c011b947a1822d3R153-R154): Introduced new environment variables `ghapp-nuclia-service-bot-id` and `ghapp-nuclia-service-bot-pk` under the `jobs` section to support the deployment process.
=> Enable new docker build pipeline with provenance and sbom scanning

.github/workflows/deploy.yml, apps/manager-v2/src/app/app.component.ts
This pull request includes a change to the `.github/workflows/deploy.yml` file to improve the deployment process by conditionally skipping context creation.
* [`.github/workflows/deploy.yml`](diffhunk://#diff-28802fbf11c83a2eee09623fb192785e7ca92a3f40602a517c011b947a1822d3L196-R196): Modified the `skip-context-creation` parameter to be conditional based on the outputs of the `check-deploy` step.
=> Fix context creation when is not created first

charts/app/templates/app.vs.yaml, charts/app/values.yaml
This pull request includes changes to the `charts/app/templates/app.vs.yaml` and `charts/app/values.yaml` files to enhance the configuration flexibility of the virtual service. The most important changes include adding support for extra match rules and consolidating the HTTP match and retry configurations.
Enhancements to virtual service configuration:
* [`charts/app/templates/app.vs.yaml`](diffhunk://#diff-94f163a7a731d9cc380dca5441095e6476e11f9325bea287779f7891298a8d50R18-R26): Added support for extra match rules by introducing a new `extraMatch` section and refactored the existing match and retry configurations to use templated YAML.
* [`charts/app/values.yaml`](diffhunk://#diff-dfbca39ca13a7dd62bff1bd65a1ea1aa719d16eb5ccda48ef12a2eead0bf865fR37-R62): Introduced new configuration …
=> Dashboard chart: Make HTTP routes configurable

libs/common/common.babel, libs/common/src/assets/i18n/ca.json, libs/common/src/assets/i18n/en.json, libs/common/src/assets/i18n/es.json, libs/common/src/assets/i18n/fr.json, libs/common/src/lib/tasks-automation/task-details/task-testing/task-testing.component.html, libs/common/src/lib/tasks-automation/task-details/task-testing/task-testing.component.ts
=> Revert "disable testing with keyword or label filtering"

apps/dashboard/src/app/retrieval-agent/agent-dashboard/agent-dashboard.component.scss, apps/dashboard/src/app/retrieval-agent/agent-dashboard/agent-dashboard.component.ts, apps/dashboard/src/app/retrieval-agent/agent-dashboard/workflow/basic-elements/node-box/node-box.component.scss, apps/dashboard/src/app/retrieval-agent/agent-dashboard/workflow/basic-elements/node-box/node-box.component.ts, apps/dashboard/src/app/retrieval-agent/agent-dashboard/workflow/workflow.effects.ts, apps/dashboard/src/app/retrieval-agent/agent-dashboard/workflow/workflow.service.ts, apps/dashboard/src/app/retrieval-agent/agent-dashboard/workflow/workflow.state.ts
- Prevent node links to cross each others
- Highlight unsaved nodes
=> [sc-12121] arag editor improvements

apps/dashboard/src/app/account/account-arag/arag-list/arag-list.component.ts, apps/manager-v2/src/app/manage-accounts/account-details/account-details.component.html, apps/manager-v2/src/app/manage-accounts/account-details/configuration/configuration.component.html, apps/manager-v2/src/app/manage-accounts/account-details/configuration/configuration.component.ts, apps/manager-v2/src/app/manage-accounts/account-ui.models.ts, apps/manager-v2/src/app/manage-accounts/account.service.ts, apps/manager-v2/src/app/manage-accounts/global-account.models.ts, apps/manager-v2/src/app/manage-accounts/global-account.service.ts, apps/manager-v2/src/app/manage-accounts/regional-account.models.ts, apps/manager-v2/src/app/manage-accounts/regional-account.service.ts, libs/core/src/lib/models/account.model.ts, libs/sdk-core/src/lib/db/db.models.ts
- Manage max arags limit on manager
- Use arag limit in arag list page in dashboard
=> [sc-12332] add max arags limit in manager

apps/dashboard/src/app/retrieval-agent/agent-dashboard/workflow/basic-elements/connectable-entry/connectable-entry.component.scss, apps/dashboard/src/app/retrieval-agent/agent-dashboard/workflow/basic-elements/link/link.component.ts, apps/dashboard/src/app/retrieval-agent/agent-dashboard/workflow/basic-elements/node-box/node-box.component.scss, apps/dashboard/src/app/retrieval-agent/agent-dashboard/workflow/basic-elements/node-box/node-box.component.ts, apps/dashboard/src/app/retrieval-agent/agent-dashboard/workflow/sidebar/test-agent/test-panel.service.ts, apps/dashboard/src/app/retrieval-agent/agent-dashboard/workflow/workflow.models.ts, libs/common/src/lib/select-account-kb/select-kb/select-kb.component.html, libs/sdk-core/src/lib/db/retrieval-agent/retrieval-agent.models.ts, libs/sdk-core/src/lib/db/retrieval-agent/retrieval-agent.ts
- Add processing state color to links and input/output circles
- Fix KB select page: display arag list when the user doesn't have access to any KB, but have access to some arags
- Add method in SDK allowing to interact with the session using HTTP POST
=> [sc-12307] retrieval agent test and interactions 3

libs/common/src/lib/retrieval-agent/agent-dashboard/workflow/sidebar/test-agent/test-panel.component.html, libs/common/src/lib/retrieval-agent/agent-dashboard/workflow/sidebar/test-agent/test-panel.component.ts, libs/common/src/lib/retrieval-agent/agent-dashboard/workflow/sidebar/test-agent/test-panel.service.ts, libs/common/src/lib/retrieval-agent/agent-dashboard/workflow/workflow.service.ts, libs/common/src/lib/retrieval-agent/agent-dashboard/workflow/workflow.state.ts
- Make sure to enable the question after the first answer so we can run another session.
- Disable full question form (including session select and run button) when running a test
- Reset test panel when switching ARAG
=> Mpellerin/sc 12307/retrieval agent test and interactions 8

libs/common/common.babel, libs/common/src/assets/i18n/ca.json, libs/common/src/assets/i18n/en.json, libs/common/src/assets/i18n/es.json, libs/common/src/assets/i18n/fr.json, libs/common/src/lib/retrieval-agent/agent-dashboard/workflow/sidebar/test-agent/elements/agent-block/agent-block.component.html, libs/common/src/lib/retrieval-agent/agent-dashboard/workflow/sidebar/test-agent/elements/agent-block/agent-block.component.ts, libs/common/src/lib/retrieval-agent/agent-dashboard/workflow/sidebar/test-agent/elements/agent-context/agent-context.component.html, libs/common/src/lib/retrieval-agent/agent-dashboard/workflow/sidebar/test-agent/elements/agent-context/agent-context.component.scss, libs/common/src/lib/retrieval-agent/agent-dashboard/workflow/sidebar/test-agent/elements/agent-context/agent-context.component.ts, libs/common/src/lib/retrieval-agent/agent-dashboard/workflow/sidebar/test-agent/elements/agent-context/index.ts, libs/common/src/lib/retrieval-agent/agent-dashboard/workflow/sidebar/test-agent/elements/index.ts, libs/common/src/lib/retrieval-agent/agent-dashboard/workflow/sidebar/test-agent/test-panel.component.scss, libs/common/src/lib/retrieval-agent/agent-dashboard/workflow/sidebar/test-agent/test-panel.service.ts, libs/common/src/lib/retrieval-agent/agent-dashboard/workflow/workflow.state.ts, libs/sdk-core/src/lib/db/kb/kb.models.ts, libs/sdk-core/src/lib/db/kb/kb.ts, libs/sdk-core/src/lib/db/retrieval-agent/interactions.models.ts, libs/sdk-core/src/lib/db/retrieval-agent/retrieval-agent.models.ts, libs/sdk-core/src/lib/db/retrieval-agent/retrieval-agent.ts, libs/sdk-core/src/lib/db/retrieval-agent/retrieval-agent.types.ts
- Always get a new ephemeral token for websockets
- Be resilient if the connection closes before the answer is fully done
- Display context as well as steps in the test panel (Keeping the context basic: display the number of chunks but not their details)
=> [sc-12307] bug fixes on WS + display context and steps 

apps/search-widget-demo/src/App.svelte, libs/search-widget/src/common/expander/Expander.svelte, libs/search-widget/src/common/indicators/DocTypeIndicator.svelte, libs/search-widget/src/common/modal/ConfirmDialog.svelte, libs/search-widget/src/common/modal/Modal.svelte, libs/search-widget/src/common/spinner/Spinner.svelte, libs/search-widget/src/components/answer/Answer.svelte, libs/search-widget/src/components/answer/Chat.svelte, libs/search-widget/src/components/answer/JsonAnswer.svelte, libs/search-widget/src/components/knowledge-graph/Graph.svelte, libs/search-widget/src/components/knowledge-graph/KnowledgeGraph.svelte, libs/search-widget/src/components/result-row/ResultRow.svelte, libs/search-widget/src/components/viewer/SearchResultNavigator.svelte, libs/search-widget/src/components/viewer/renderers/ConversationRenderer.svelte, libs/search-widget/src/components/viewer/renderers/players/AudioPlayer.svelte, libs/search-widget/src/components/viewer/renderers/players/PlayerControls.svelte, libs/search-widget/src/components/viewer/renderers/players/VideoPlayer.svelte, libs/search-widget/src/components/viewer/renderers/players/YoutubePlayer.svelte, libs/search-widget/src/components/viewer/renderers/renderings/ExtractedTextRendering.svelte, libs/search-widget/src/components/viewer/renderers/renderings/PdfRendering.svelte, libs/search-widget/src/components/viewer/renderers/renderings/TextContentRendering.svelte, libs/search-widget/src/core/knowledge-graph.models.ts, libs/search-widget/src/core/stores/graph.store.ts, libs/search-widget/src/widgets/chat-widget/ChatWidget.svelte, libs/search-widget/src/widgets/global-widget/components/answer/Answer.svelte, libs/search-widget/src/widgets/search-widget/SearchBar.svelte, libs/search-widget/src/widgets/viewer-widget/ViewerWidget.svelte
- Replace run blocks from svelte 5 migration by proper effect/derived
- Better typing on Knowledge Graph
=> [sc-12471] remove the run blocks in svelte files

libs/common/src/lib/search-widget/search-page.component.html, libs/common/src/lib/search-widget/search-page.component.scss, libs/common/src/lib/search-widget/search-page.component.ts
- Allow the search config panel to be closed even on large screens
- Make it resizable
=> [sc-12472] make the right search panel resizable

libs/common/src/lib/search-widget/search-configuration/generative-answer-form/generative-answer-form.component.html, libs/common/src/lib/search-widget/search-configuration/search-configuration.component.html, libs/common/src/lib/search-widget/search-configuration/search-configuration.component.scss, libs/common/src/lib/search-widget/search-configuration/search-configuration.component.ts, libs/common/src/lib/search-widget/search-page.component.html, libs/common/src/lib/search-widget/search-page.component.scss, libs/common/src/lib/search-widget/search-page.component.ts, mrs.developer.json
- allow to reduce the search config panel size
- fix panel left border position when scrolling inside the panel
=> [sc-12472] allow to reduce the search config panel size

libs/common/src/lib/retrieval-agent/agent-dashboard/workflow/workflow.models.ts
=> Add fallback to mcp agent

libs/common/src/lib/retrieval-agent/agent-dashboard/workflow/nodes/mcp/mcp-node.component.html, libs/common/src/lib/retrieval-agent/agent-dashboard/workflow/nodes/mcp/mcp-node.component.ts, libs/common/src/lib/retrieval-agent/agent-dashboard/workflow/workflow.service.ts, libs/sdk-core/src/lib/db/retrieval-agent/retrieval-agent.models.ts
=> [ARAG] missing

libs/common/src/lib/retrieval-agent/agent-dashboard/workflow/basic-elements/node-form/field-config.service.ts, libs/common/src/lib/retrieval-agent/agent-dashboard/workflow/basic-elements/node-form/field-renderer/field-renderer.component.html, libs/common/src/lib/retrieval-agent/agent-dashboard/workflow/basic-elements/node-form/field-renderer/field-renderer.component.ts, libs/common/src/lib/retrieval-agent/agent-dashboard/workflow/basic-elements/node-form/node-form.component.ts, libs/common/src/lib/retrieval-agent/agent-dashboard/workflow/basic-elements/node-form/subcomponents/index.ts, libs/common/src/lib/retrieval-agent/agent-dashboard/workflow/basic-elements/node-form/subcomponents/key-value-field/index.ts, libs/common/src/lib/retrieval-agent/agent-dashboard/workflow/basic-elements/node-form/subcomponents/key-value-field/key-value-field.component.html, libs/common/src/lib/retrieval-agent/agent-dashboard/workflow/basic-elements/node-form/subcomponents/key-value-field/key-value-field.component.scss, libs/common/src/lib/retrieval-agent/agent-dashboard/workflow/basic-elements/node-form/subcomponents/key-value-field/key-value-field.component.ts, libs/common/src/lib/retrieval-agent/agent-dashboard/workflow/workflow.service.ts, libs/common/src/lib/retrieval-agent/drivers/drivers.service.ts
SC-13194; Agent Form - MCP - root component override; 
SC-13199; Driver Form - NucliaDB - Use hardcoded form;
=> SC-13194; SC-13199;
